mlc-ai/web-llm

build.py
chat.py
evaluate.py
scripts/build_site.sh
scripts/local_deploy_site.sh
scripts/rpc_debug_deploy.sh
site/index.md
web/gh-page-config.json
web/llm_chat.js
web/local-config.json
web_llm/conversation.py
web_llm/transform/dispatch_tir_operator.py

Vicuna v0's vocab_size is 32001, but v1's vocab size is 32000. So we need to update the manual schedule.

Change vocab size to support vicuna v1

---

build.py
chat.py
web/llm_chat.js
web_llm/relax_model/llama.py

This PR changes the creation of KV cache so that it becomes a VM function that will be invoked before generation.

KV cache creation as a separate func

---

web_llm/utils.py

Use default max_sequence_length

---

web/llm_chat.js

fix: Change output to textContent.

---

README.md

docs: Update README.md / typo fix

---

build.py
scripts/build_site.sh
scripts/local_deploy_site.sh
scripts/rpc_debug_deploy.sh
web_llm/conversation.py
web_llm/utils.py

Added support for building WizardLM

feat: support WizardLM

---

README.md
web/llm_chat.js

This PR update the term name: encoding->prefill so that it is consistent with mlc-llm

Use prefill for term consistency 

---

site/_includes/llm_chat.html
site/index.md
web/llm_chat.html
web/llm_chat.js

1. clear all chat history when switching model
2. ban user input model url temporarily

improve model selector

---

README.md
examples/README.md
examples/simple-chat/README.md
examples/simple-chat/src/gh-config.js
examples/simple-chat/src/llm_chat.html
examples/simple-chat/src/mlc-local-config.js
examples/simple-chat/src/simple_chat.ts
examples/simple-chat/src/worker.ts
examples/web-worker/README.md
examples/web-worker/package.json
examples/web-worker/src/get_started.html
examples/web-worker/src/main.ts
examples/web-worker/src/worker.ts
package-lock.json
package.json
src/index.ts
src/web_worker.ts

This PR introduces webworker support to WebLLM package.

Introduce builtin WebWorker support

---

examples/simple-chat/src/gh-config.js
site/index.md
src/chat_module.ts
src/config.ts
src/conversation.ts
src/llm_chat.ts

This PR introduces the 7B and 13B Llama 2 model support, including f16 and f32 for each model.

[Model] Llama 2 support

---

examples/simple-chat/src/gh-config.js

This PR supports Web LLM with 70B Llama 2 model.

Support Llama 2 70B

---

src/chat_module.ts
src/index.ts

**NOTE**: This depends on https://github.com/mlc-ai/relax/pull/265 and cannot be merged before that PR is merged.

add helper methods to check cache

---

examples/simple-chat/src/gh-config.js
src/conversation.ts

Add the following wizard models to `simple chat` in web llm:
- WizardCoder-15B-V1.0-q4f16_1
- WizardCoder-15B-V1.0-q4f32_1
- WizardMath-7B-V1.0-q4f16_1
- WizardMath-7B-V1.0-q4f32_1
- WizardMath-13B-V1.0-q4f16_1
- WizardMath-70B-V1.0-q4f16_1

Add wizard models to simple chat

---

site/_config.yml
site/index.md

Fixed case: Github -> GitHub

---

examples/README.md

Thank you for this great project and your work. I built this chat app prototype around WebLLM and deployed it on the decentralized cloud platform Internet Computer (so the frontend and the backend are hosted decentrally). If you like, this PR adds it as a demo example. Thanks.

Add DeVinci chat app as demo example

---

examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json

Bump version to 0.2.10 to reflect dependencies on new version of @mlc-ai/web-tokenizers

[Version] Bump version to 0.2.10

---

examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json

The main change includes compatibility with models compiled with the new mlc-llm workflow SLIM.

[Version] Bump version to 0.2.11

---

examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json
src/conversation.ts

Update support for Neural Hermes Mistral.

[Version] Bump version to 0.2.12

---

examples/simple-chat/README.md

I'm submitting this pull request to address the concerns raised in issue#236

Update instructions of simple-chat for windows users

---

examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json

Bump version to 0.2.15. Changes include:
- Full migration to SLM
- Reflect change in tvmjs runtime: https://github.com/mlc-ai/relax/commit/b1df4b085608158b451d4777743d63f9fab3e0e3
- UI changes: scrollbar and separator for model drop down menu

[Version] Bump version to 0.2.15

---

examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/logit-processor/package.json
examples/openai-api/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

Main change is Gemma supprt:
https://github.com/mlc-ai/web-llm/pull/305
https://github.com/mlc-ai/web-llm/pull/306

[Version] Bump version to 0.2.21

---

examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/logit-processor/package.json
examples/openai-api/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

The only change is adding optional `buffer_size_required_bytes` to `ModelRecord`.

[Version] Bump to 0.2.22

---

examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/logit-processor/package.json
examples/openai-api/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

[Version] Bump version to 0.2.23

---

examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/get-started-rest/package.json
examples/get-started/package.json
examples/logit-processor/package.json
examples/openai-api/package.json
examples/simple-chat/package.json
examples/web-worker/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

The new version include 2 changes:
- Include cache deletion API via https://github.com/mlc-ai/web-llm/pull/314
- Fix model download/caching issue on TVMjs side via https://github.com/apache/tvm/pull/16650

[Version] Bump version to 0.2.24

---

examples/chrome-extension-webgpu-service-worker/README.md

This PR updates Chrome Extension using WebGPU Service Worker README.md following https://github.com/gpuweb/gpuweb/issues/4197#issuecomment-1999149752
@rickzx @tqchen

Update Chrome Extension using WebGPU Service Worker README.md

---

src/chat_module.ts
src/config.ts
src/conversation.ts
src/llm_chat.ts
tests/conv_template.test.ts
tests/function_calling.test.ts

cc: @CharlieFRuan
Need to rebase after https://github.com/mlc-ai/web-llm/pull/321 is merged.

Update conversation template to use the unified schema

---

.gitignore
README.md
examples/get-started-web-worker/src/main.ts
examples/get-started/src/get_started.ts
examples/json-mode/src/json_mode.ts
examples/multi-round-chat/src/multi_round_chat.ts
examples/next-simple-chat/src/utils/chat_ui.ts
examples/seed-to-reproduce/src/seed.ts
examples/streaming/src/streaming.ts
src/config.ts
src/engine.ts

Add Llama 3 8B and 70B to `webllm.prebuiltAppConfig`. Update examples from Llama 2 Chat 7b to Llama 3 Instruct 8b

[Llama3] Add Llama 3 to prebuilt

---

README.md

I added the model Llama-3 on README file of repository

feat: added support Llama-3 on README file

---

src/types.ts

chore: update types.ts

---

.gitignore
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/function-calling/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat/package.json
examples/streaming/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

Main changes include:
- New model `Hermes-2-Pro-Mistral-7B` in `prebuiltAppConfig` via:
- https://github.com/mlc-ai/web-llm/pull/390
- Various `index.js` and `index.js.map` post-processings to resolve frontend compatibility issues with `require()` and `perf_hoooks`
- https://github.com/mlc-ai/web-llm/pull/397
- https://github.com/mlc-ai/web-llm/pull/406
- Catch WebGPU OOM error upon `reload()` and `CreateEngine()`:
- https://github.com/mlc-ai/web-llm/pull/402
- Service Worker support (in addition to Extension Service Worker):
- https://github.com/mlc-ai/web-llm/pull/395
- https://github.com/mlc-ai/web-llm/pull/400
- https://github.com/mlc-ai/web-llm/pull/401
v0_2_34 as no change is required.
TVMjs compiled at https://github.com/apache/tvm/commit/a5862a5c696a3237f644f31bc312aae303213f3f, …

[Version] Bump version to 0.2.36

---

examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/function-calling/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat/package.json
examples/streaming/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

The only two changes are:
- https://github.com/mlc-ai/web-llm/pull/413
- https://github.com/mlc-ai/web-llm/pull/415
- Fixes `index.js.map` issue in Vite reported in https://github.com/mlc-ai/web-llm/issues/414
v0_2_34 as no change is required.
TVMjs compiled at https://github.com/apache/tvm/commit/a5862a5c696a3237f644f31bc312aae303213f3f, with no change

[Version] Bump version to 0.2.38

---

site/_includes/hero.html
site/assets/css/hero.scss

This PR fixes some small css issues on the landing page and also adds feature to only play the video when it's visible to users.

[Site] Play video only when visible

---

scripts/prep_deps.sh

Rename `TVM_HOME` to `TVM_SOURCE_DIR` for build from source script `prep_deps.sh` as per https://github.com/mlc-ai/mlc-llm/pull/2378

[Fix] Rename TVM_HOME TVM_SOURCE_DIR

---

src/service_worker.ts

This PR updates the implementation of service worker classes to simplify the code. This has no functional difference.
Tested on https://chat.webllm.ai

[ServiceWorker] Refactor implementation

---

src/extension_service_worker.ts

Fixes:
- #479 Allow specifying optional extensionId when creating ServiceWorkerMLCEngine
- #480 Allow specifying optional onDisconnect callback when creating ServiceWorkerMLCEngine
Use case see ticket #479 
Tested with the following setup:
- Create an extension the [`unlimitedStorage` permission](https://developer.chrome.com/docs/extensions/develop/concepts/storage-and-cookies), [externally_connectable](https://developer.chrome.com/docs/extensions/reference/manifest/externally-connectable) and the follow background script
```typescript
import { ExtensionServiceWorkerMLCEngineHandler } from "@mlc-ai/web-llm";
// Hookup an engine to a service worker handler
let handler;
chrome.runtime.onConnectExternal.addListener(function (port) {
if (port.name !== "web_llm_service_worker") { …
```

Fixes #479 & #480 Allow specifying optional `extensionId` & `onDisconnect` callback when creating ServiceWorkerMLCEngine

---

src/cache_util.ts
src/config.ts
src/engine.ts
src/error.ts
src/extension_service_worker.ts
src/llm_chat.ts
src/openai_api_protocols/chat_completion.ts
src/service_worker.ts
src/web_worker.ts

This PR adds custom error types to the repo so that users could easily catch specific kinds of errors.

style: Add custom error types

---

src/config.ts

Add `q0f16`, `q0f32`, `q4f16_1`, `q4f32_1` for each of the three sizes.

[Model] Add SmoLM models

---

examples/simple-chat-ts/src/simple_chat.ts
src/config.ts

Add gemma-2 2b and 9b to prebuilt models, kept old gemma as well.

[Model] Add gemma-2 2b and 9b

---

src/config.ts

Add `Hermes-2-Theta-Llama-3-8B-q4f16_1-MLC` and `Hermes-2-Theta-Llama-3-8B-q4f32_1-MLC` to the prebuilt model list.

[Model] Add Hermes-2-Theta 8B

---

examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

No breaking changes. The only delta are the following two PRs:
- https://github.com/mlc-ai/web-llm/pull/523
- https://github.com/mlc-ai/web-llm/pull/527
- Added example for manual function calling without using the `tools` fields
TVMjs
No change, compiled at https://github.com/apache/tvm/commit/e6476847753c80e054719ac47bc2091c888418b6

[Version] Bump version to 0.2.53

---

examples/abort-reload/package.json
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

No breaking changes. The only diff is the following PR:
- https://github.com/mlc-ai/web-llm/pull/525
- This PR updates the engine reload() and unload() methods to allow users to abort an uncompleted reload() by either:
- call unload() any time before reload() completed
- call reload() again before the previous reload() completed
- Besides, it fixes the previous issue where `device lost error` is raised unexpectedly when user simply switches a model
- To support the above PR, TVMjs is updated and compiled at https://github.com/apache/tvm/commit/1fcb62023f0a5f878abd5b43ec9e547933fb5fab
- Difference:
- Device error lost fix: https://github.com/apache/tvm/pull/17250
- Add AbortSignal to fetching APIs:
- https://github.com/apache/tvm/pull/17208
- https://github.com/apache/tvm/pull/17227
- …

[Version] Bump to version 0.2.54

---

examples/abort-reload/package.json
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

No breaking changes. The only delta is the addition of Qwen2-Math 1.5B and 7B:
- https://github.com/mlc-ai/web-llm/pull/531
No change, compiled at https://github.com/apache/tvm/commit/1fcb62023f0a5f878abd5b43ec9e547933fb5fab

[Version] Bump version to 0.2.55

---

examples/abort-reload/package.json
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
examples/text-completion/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

- Reorganized internal code, which should have no affect on behaviors https://github.com/mlc-ai/web-llm/pull/536
- Bumped version of tokenizers-cpp to fix potential error `The global thread pool has not been initialized.`
- For more, see https://github.com/mlc-ai/tokenizers-cpp/pull/42
- Still compiled at https://github.com/apache/tvm/commit/1fcb62023f0a5f878abd5b43ec9e547933fb5fab, no change

[Version][Trivial] Bump version to 0.2.57

---

examples/abort-reload/package.json
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/embeddings/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-models/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
examples/text-completion/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

- https://github.com/mlc-ai/web-llm/pull/541
- https://github.com/mlc-ai/web-llm/pull/542
- When single model loaded, no change in behavior
- When multiple models loaded, some APIs need to specify which model it is targeting
- For more, see PR description (the user-facing section)
- Also see `examples/multi-models`
Still compiled at https://github.com/apache/tvm/commit/1fcb62023f0a5f878abd5b43ec9e547933fb5fab, no change

[Version] Bump version to 0.2.59

---

examples/abort-reload/package.json
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/embeddings/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-models/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
examples/text-completion/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

- https://github.com/mlc-ai/web-llm/pull/546
- Fix WebWorker's async generator, supporting concurrent generation from different models in the same engine
- See the PR description, the demo in the reply, and `examples/multi-models` for more
Still compiled at https://github.com/apache/tvm/commit/1fcb62023f0a5f878abd5b43ec9e547933fb5fab, no change

[Version][Trivial] Bump version to 0.2.60

---

examples/chrome-extension/README.md
examples/chrome-extension/package.json
examples/chrome-extension/src/content.js
examples/chrome-extension/src/manifest.json
examples/chrome-extension/src/popup.css
examples/chrome-extension/src/popup.html
examples/chrome-extension/src/popup.ts

- updated manifest.json to include content.js (enabling reading of page contents as context)
- extended extension functionality to include all available MLC models
- aesthetics changes to the UI, 
- included loading text and loading bar that appears as models are loaded in
- included a Now Chatting With text that displays the model that we are currently chatting with

Modified chrome extension

---

src/config.ts

Add the following model to prebuilt list:
- `Qwen2.5-Math-1.5B-Instruct-q4f16_1-MLC`
- `Qwen2.5-Math-1.5B-Instruct-q4f32_1-MLC`

[Model] Add Qwen2.5-1.5B Math

---

README.md
examples/abort-reload/package.json
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/embeddings/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-models/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
examples/text-completion/package.json
examples/vision-model/package.json
examples/vision-model/src/vision_model.ts
examples/vision-model/src/worker.ts
package-lock.json
package.json
utils/vram_requirements/package.json

- https://github.com/mlc-ai/web-llm/pull/574
- Enable image input for web/service worker
- No change, version `0.18.0-dev0` just like 0.2.66
- Built at https://github.com/apache/tvm/commit/30fb16a5e1d564ffa8533cf154c0ba2ea06dfd43

[Version] Bump version to 0.2.68

---

README.md
examples/abort-reload/package.json
examples/cache-usage/package.json
examples/chrome-extension-webgpu-service-worker/package.json
examples/chrome-extension/package.json
examples/embeddings/package.json
examples/function-calling/function-calling-manual/package.json
examples/function-calling/function-calling-openai/package.json
examples/get-started-web-worker/package.json
examples/get-started/package.json
examples/json-mode/package.json
examples/json-schema/package.json
examples/logit-processor/package.json
examples/multi-models/package.json
examples/multi-round-chat/package.json
examples/next-simple-chat/package.json
examples/seed-to-reproduce/package.json
examples/service-worker/package.json
examples/simple-chat-ts/package.json
examples/streaming/package.json
examples/text-completion/package.json
examples/vision-model/package.json
package-lock.json
package.json
utils/vram_requirements/package.json

- The only change is https://github.com/mlc-ai/web-llm/pull/584

[Version][Trivial] Bump version to 0.2.72

---

src/config.ts

Add the following model to prebuilt model ID:
- `gemma-2-2b-jpn-it-q4f16_1-MLC`
- `gemma-2-2b-jpn-it-q4f32_1-MLC`
See https://github.com/mlc-ai/binary-mlc-llm-libs/pull/143.

[Model] Add gemm-2-2b-jpn-it

---

README.md

Corrected "dynamicall" to "dynamically" in [README.md].
This pull request addresses a minor typo found in the repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.
This change is purely cosmetic and does not affect functionality.

Doc: Fixed Typo
