- web_llm/transform/dispatch_tir_operator.py
This PR adds the function annotation to those TIR functions after scheduling, so that the default GPU schedule pass will skip them. These annotations are missed to add before.
This PR reindent some of the PrimFunc TVMScript to remove the redundant indents.
> Minor patch on the annotation and indents of TIR func dispatch

- web_llm/transform/dispatch_tir_operator.py
- web_llm/transform/transpose_matmul.py
This PR fixes a known issue of the TE legalization func of matmul, which is used here in the generation of NT matmul. With this PR, there will be no index 0 whenever the matmul on the particular dimension is not broadcasting.
> Fix the legalization func of matmul to avoid zero index

- build.py
- chat.py
- web/gh-page-config.json
- web/llm_chat.js
- web/local-config.json
- web_llm/conversation.py
- web_llm/relax_model/llama.py
- web_llm/transform/dispatch_tir_operator.py
Currently, when user enter an input, the behavior is to clear KV cache and collect all previous conversation history as input prompt to the model. It becomes extremely slow when the history is large. But clearly, there exists some redundant kv computation for previous conversations. We could utilize the kv cache from the last round of conversation to avoid kv recomputation. This PR enables such optimization.
> Enable KV cache reuse across conversations

- web/llm_chat.js
While integrating this into a Next.js project I noticed that when it tried to run `self.updateLastMessage` it would crash Webpack in general and nothing else would load. Converting this to an arrow function to maintain the existing `this` binding fixed my issue. I'd reported this in https://github.com/mlc-ai/web-llm/issues/52.
> Use arrow function to avoid new `this` binding

- web/llm_chat.js
After `asyncOnReset` I was getting an error when trying to start a new conversation. After some trial and error I've found that `kvCacheLength` being reset to `0` fixed the issue. Based on the discussion in https://github.com/mlc-ai/web-llm/issues/83 I have created this PR to upstream the fix that worked for me.
> Reset kvCacheLength on #clearKVCache

- src/chat_module.ts
- src/config.ts
- src/conversation.ts
- src/llm_chat.ts
- src/types.ts
I've added the ability to customize more configuration options, as well as the conversation options. I couldn't build the project as I had issues with it looking for `tvm_home`, so I have not tested this and would like some feedback on if this code makes sense.
I've created this as suggested in https://github.com/mlc-ai/web-llm/issues/115, fyi @tqchen.
> Allow configuring conversation

- examples/get-started-rest/README.md
- examples/get-started-rest/package.json
- examples/get-started-rest/src/get_started.html
- examples/get-started-rest/src/get_started.ts
- examples/simple-chat/README.md
- examples/simple-chat/src/simple_chat.ts
- src/chat_module.ts
- src/index.ts
This PR adds a new `ChatRestModule` that integrates with the Python REST server. It supports both streaming and non-streaming modes.
**Getting Started Demo:**
https://github.com/mlc-ai/web-llm/assets/11940172/24421ef7-f311-474f-a1c7-683515d3755a
**Simple Chat Demo:**
https://github.com/mlc-ai/web-llm/assets/11940172/b6c1a08f-8f72-4d1e-84d7-82fa79746354
> Add local server support for WebLLM

- examples/next-simple-chat/package.json
As described in https://github.com/mlc-ai/web-llm/issues/140, for some reason the prebuilt package isn't working.
> Revert change to next example which used the prebuilt package. 

- src/config.ts
We recently rebuilt the prebuilt model weights and wasm libraries per some latest changes in Relax VM and MLC-LLM. This PR updates the lib map to point to the latest wasm libraries.
> Update model lib map for latest prebuilt wasm

- tsconfig.json
I have changed `tsconfig.json` file to fix the warning caused by unspecified `moduleResolution` field. 
The following is a wildly used and strongly typed package. The author has comment on the config file on each field why he did what
https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/tsconfig.base.json
The original tsconfig.json will cause the following error:
> feat: change tsconfig file for mordern typescript package publish

- cleanup-index-js.sh
- package.json
The string `const{createRequire:createRequire}=await import('module');` needs to be removed from `index.js` and `index.js.map` when running `npm run build`, so that the background worker in the chrome extension can run the `ChatModule`.
> Add cleanup script to remove import from index.js

- src/chat_module.ts
Based on https://github.com/mlc-ai/web-llm/issues/124 & https://github.com/mlc-ai/web-llm/issues/162 I thought we could fallback to `globalThis.location.origin` when there is no `document` like in a Web Worker.
> Don't use document in Worker

- examples/chrome-extension/package.json
- package-lock.json
- package.json
Bump the version to 0.2.7. Forgot to bump it in https://github.com/mlc-ai/web-llm/pull/180.
I've published this to https://www.npmjs.com/package/@mlc-ai/web-llm/v/0.2.7?activeTab=versions.
> Bump version to 0.2.7

- examples/chrome-extension/src/background.ts
- examples/chrome-extension/src/content.js
- examples/chrome-extension/src/example.html
- examples/chrome-extension/src/manifest.json
- examples/chrome-extension/src/popup.ts
This PR adds support for stuff QA using the context in the active tab. Note that this currently only works with the local server usage.
The example below shows a sample usage of chatting with the LLM using the contents of the active tab, which contains an AI-generated story.
[Screencast from 09-01-2023 10:24:20 AM.webm](https://github.com/mlc-ai/web-llm/assets/11940172/ec348bf1-781c-42d7-ab58-8b53dce12832)
> Add support for stuff QA using context in active tab

- src/conversation.ts
In case we don't want to provide the `conv_template` name, we can use `custom` and pass every the entire ConvTemplateConfig data instead.
> feat: custom conv_template

- examples/simple-chat/src/gh-config.js
- src/conversation.ts
- src/llm_chat.ts
This PR adds support for Mistral. The implementation follows [the Mistral paper](https://arxiv.org/abs/2310.06825), specifically including sliding window attention (SWA), rolling buffer cache, and chunking, as discussed in Section 2 in the paper. 
This PR is largely analogous to the changes in `llm_chat.cc` in mlc-llm's PR https://github.com/mlc-ai/mlc-llm/pull/1087.
Different from the approaches in https://github.com/mlc-ai/web-llm/issues/202, this PR's implementation takes advantage of SWA, so that there is no max window size anymore--one of the main benefits of Mistral.
Tested:
- Works well with:
- 4096 sliding window size, with 1024 chunk size
- Note that the small chunk size has no effect on generated output, but only less memory requirement with slower speed
- 2048 sliding window …
> [Mistral][SWA] Add Mistral sliding window support

- examples/simple-chat/src/gh-config.js
- src/chat_module.ts
This PR adds three models with 1k context length that can be run by devices with `maxStorageBufferBindingSize = 128MB`:
- `Llama-2-7b-chat-hf-q4f16_1-1k`
- `RedPajama-INCITE-Chat-3B-v1-q4f16_1-1k`
- `RedPajama-INCITE-Chat-3B-v1-q4f32_1-1k`
This is enabled by https://github.com/apache/tvm/pull/16108, and offers a temporary solution for https://github.com/mlc-ai/web-llm/issues/209 and the discussion in https://github.com/apache/tvm/pull/14640.
Irrelevantly, we also update RedPajama models from `_0` quantization to `_1`.
cc: @tqchen @beaufortfrancois @DustinBrett
> Add 128MB buffer size friendly models

- README.md
- examples/get-started/src/get_started.ts
- examples/next-simple-chat/src/utils/chat_ui.ts
- examples/simple-chat/src/gh-config.js
- examples/simple-chat/src/mlc-local-config.js
- examples/web-worker/src/main.ts
- src/config.ts
- src/conversation.ts
- src/llm_chat.ts
Make web-llm runtime compatible with SLIM models, a new workflow in mlc-llm. This depends on https://github.com/apache/tvm/pull/16198 and is currently not backward-compatible with non-SLIM model, since we introduced a new global function to TVM.
The main difference is reading the metadata and loading the parameters.
Besides, we now read stop_tokens from the conversation template instead of relying on metadata.
> [SLIM] Make web-llm compatible with SLIM models

- src/llm_chat.ts
As per changes in mlc-llm's SLIM, we rename `max_window_size` to `context_window_size`. Hence this PR, which is also backward compatible.
> [Fix][SLIM] Context window size renaming

- site/index.md
Now that the "shader-f16" feature is [enabled by default](https://developer.chrome.com/blog/new-in-webgpu-120#support_for_16-bit_floating-point_values_in_wgsl) in Chrome, we can clean the Chrome-specific instructions.
> Clean chrome browser instructions

- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
Bump version to 0.2.14. Main changes include:
- Fix wizard math conversation template
- Change the way we map model weights and model library (deprecate model lib map)
- FIx Mistral models template
- Fix tokenizer issue (especially stop token)
> [Version] Bump version to 0.2.14

- examples/simple-chat/src/llm_chat.css
Due to previously neglecting to check the scrollbar's appearance during long conversations, I discovered that its color remained white, which didn't quite fit with the overall theme. Therefore, I have made a small adjustment to the color.
FROM
TO
> Change scrollbar track color in chat UI

- examples/simple-chat/src/simple_chat.ts
This PR show separators in chat model selector so that it's easier to read for users.
> Show separators in chat model selector

- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Bump version to 0.2.16; changes include:
- Disabling the selection of certain models on low-resource devices (e.g. Android phone), exposing a new API `getMaxStorageBufferBindingSize()`
- https://github.com/mlc-ai/web-llm/pull/256
- Added TinyLlama (including the chatml conversation template)
> [Version] Bump version to 0.2.16

- examples/simple-chat/src/llm_chat.css
Currently, when viewing the demo page https://webllm.mlc.ai/ on an Android phone, there is a grey bar. This PR removes it. Tested on Samsung Galaxy S23.
> [SimpleChat] Small fix on Android UI

- examples/simple-chat/src/simple_chat.ts
- src/chat_module.ts
- src/types.ts
- src/web_worker.ts
As a follow-up to https://github.com/mlc-ai/web-llm/pull/256, which fails to detect that we are using low-resource device as some Android phones have 2GB `maxStorageBufferBindingSize` (e.g. Pixel 7), this PR use the vendor shown in https://webgpureport.org/ to determine whether we are on low-resource device, hence limiting the selectable models.
For now, we have `qualcomm` and `arm`, which should at least cover most Pixel and most Samsung Galaxy S.
> [SimpleChat] Check vendor to determine mobile environment

- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
New version 0.2.17 includes a new API in ChatModule `getGPUVendor()` and support for phi models.
> [Version] Bump version to 0.2.17

- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/logit-processor/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Bump version to 0.2.18; main changes include:
- Add LogitProcessor, allowing implicit logits manipulation before sampling
- Expose low-level API `forwardTokensAndSample()`
- Support `customRequest` in web worker
See https://github.com/mlc-ai/web-llm/pull/277 for more details.
> [Version] Bump version to 0.2.18

- src/conversation.ts
- Adds qwen
- Adds stablels-3b
- Adds stablelm-2
- Fixes chatml not able to be extended with config json
> Conversation templates for Qwen and StableLM

- src/chat_module.ts
- src/llm_chat.ts
PagedKVCache is introduced in MLC-LLM a while back to unite the interface for KVCache. This PR makes WebLLM compatible with the new PagedKVCache interface, encapsulating it with the goal that WebLLM users will not notice any difference.
This PR is equivalent to the changes to `llm_chat.cc` in https://github.com/mlc-ai/mlc-llm/pull/1651, and should address issues like https://github.com/mlc-ai/mlc-llm/issues/1628.
There are still existing model compilation issues regarding `workgroup_size` (since WebGPU, unlike most other backends, can only support 256 number of threads). We will address this issue more elegantly soon; for now, compiling llama-based models require manually changing kernel sizes as shown in [this branch](https://github.com/CharlieFRuan/mlc-llm/tree/local-workgroupSize-webLLM …
> [LLMChat] Make llm_chat compatible with PagedKVCache

- examples/get-started-rest/package.json
- examples/get-started/src/get_started.ts
- jest.config.cjs
- package-lock.json
- package.json
- src/chat_module.ts
- src/config.ts
- src/index.ts
- src/llm_chat.ts
- src/types.ts
- src/web_worker.ts
- tests/generation_config.test.ts
This PR adds `GenerationConfig`, which allows per-generation configs. See `get-started.ts` for its example usage:
```typescript
let genConfig: webllm.GenerationConfig = {
presence_penalty: 0.5,
frequency_penalty: 0.5,
max_gen_len: 20,
// stop: ["is", "Canada"]  // for demonstration purpose
}
const prompt0 = "What is the capital of Canada?";
const reply0 = await chat.generate(prompt0, generateProgressCallback, 1, genConfig);
```
In addition to the existing fields in `mlc-chat-config.json`, we also support OpenAI-like fields `frequency_penalty`, `presence_penalty`, and `stop` to prepare for the incoming OpenAI-like APIs.
This PR also sets up unit tests; use `npm test` to run tests. However, some work needs to be done to support end-to-end testing (e.g. accessing WebGPU in a test …
> [ChatModule] Add GenerationConfig and set up unit tests

- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/logit-processor/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
The new version includes two main changes:
1. We now support models compiled with `PagedKVCache` (only Llama-variants for now)
- This is breaking in the sense that, in order to use the update Llama WASMs, an update to the WebLLM npm is required
- WASMs updated here: https://github.com/mlc-ai/binary-mlc-llm-libs/pull/90
- For more see https://github.com/mlc-ai/web-llm/pull/293
2. We now support `GenerationConfig`, allowing configuring each generation (e.g. repetition penalty, temperature, etc.)
- All WASMs needed to be recompiled since we included new function `ApplyPresenceAndRequencyPenalty()` in tvmjs
- For more see https://github.com/mlc-ai/web-llm/pull/298
Other changes include: 
- https://github.com/mlc-ai/web-llm/pull/285
> [Version] Bump version to 0.2.19

- examples/simple-chat/src/gh-config.js
- examples/simple-chat/src/simple_chat.ts
- src/config.ts
While `gemma` work on some mobile devices (e.g. Pxiel 7 Pro), other devices that have smaller `maxStorageBufferBindingSize` do not. We add the specific limit to the model record. While VRAM requirement states the total VRAM needed, buffer binding size is different such that it specifies the limit for a single storage buffer. See more at https://www.w3.org/TR/webgpu/#dom-supported-limits-maxstoragebufferbindingsize
> [SimpleChat] Limit model selections with maxStorageBufferBindingSize

- src/cache_util.ts
- src/chat_module.ts
- src/index.ts
Support async delete functions for the users
> Support Delete All Data Interface

- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/logit-processor/package.json
- examples/openai-api/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Another minor follow-up to version 0.2.24 (or hence to 0.2.25). This PR adds a `try-catch` when loading the **_already-downloaded_** weights, attempting to provide more information to the `exit(1)` error in https://github.com/mlc-ai/web-llm/issues/322.
The only change is TVMJS's commit https://github.com/apache/tvm/pull/16650/commits/b193cbbb571a45802bfddfbaf9e9c80d431de638 from https://github.com/apache/tvm/pull/16650
> [Version] Bump version to 0.2.26

- examples/openai-api/src/openai_api.ts
- examples/web-worker/src/main.ts
- src/chat_module.ts
- src/llm_chat.ts
- src/openai_api_protocols/chat_completion.ts
- src/types.ts
- src/web_worker.ts
- tests/openai_chat_completion.test.ts
This PR adds the `stateful` option to `ChatCompletionRequest`. When set to true, we preserve previous chat history, allowing multi-round chat, essentially behaving like `generate()`. Note that a stateful chat can only have `n=1`.
In addition, we expose `getMessage()` to `ChatInterface`. This allows streaming chat completion requests to extract the final response more easily (rather than manually concatenating the deltas).
> [OpenAI] Support stateful chat completion

- examples/openai-api/src/openai_api.ts
- src/chat_module.ts
- src/config.ts
- src/llm_chat.ts
- src/openai_api_protocols/chat_completion.ts
- src/support.ts
- tests/generation_config.test.ts
- tests/util.test.ts
Support `logprobs` and `top_logprobs` for OpenAI API `ChatCompletion`. Subsequently, these are added to `GenerationConfig` as well. See [this link](https://platform.openai.com/docs/api-reference/chat/create) for reference.
Implementation-wise, since we need the actual distribution, we use `tvmjs.applySoftmaxWithTemperature()` and `tvmjs.sampleTopPFromProb()` instead of `tvmjs.sampleTopPFromLogits()`.
Performance-wise, despite all sampling being done on CPU, with `top_logprobs=2`, we observe no degradation with Llama-2-7b-q4f32 on M3 Macbook. Note that without `logprobs`, exact same behavior (hence performance) is maintained.
We also support `CompletionUsage` in this PR for token counting.
> [OpenAI] Support logprobs and top_logprobs in ChatCompletion

- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/logit-processor/package.json
- examples/openai-api/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Changes in WebLLM:
- Stateful chat completion: https://github.com/mlc-ai/web-llm/pull/330
- OpenAI's `logit_bias`: https://github.com/mlc-ai/web-llm/pull/331
- OpenAI's `logprobs` and `top_logprobs`: https://github.com/mlc-ai/web-llm/pull/333
Changes in TVMjs:
- https://github.com/apache/tvm/pull/16650
- Fix param download issues (already reflected in 0.2.26, but at the time this PR was not merged yet)
- Expose `sampleTopPFromProb` to support `logprobs` (new in 0.2.27)
> [Version] Bump version to 0.2.27

- examples/openai-api/README.md
- examples/openai-api/src/seed.html
- examples/openai-api/src/seed.ts
- src/chat_module.ts
- src/llm_chat.ts
- src/openai_api_protocols/chat_completion.ts
- tests/openai_chat_completion.test.ts
We support `seed` in `ChatCompletionRequest` so requests' results are reproducible. 
As stated in the docstring in `src/openai_api_protocols/chat_completion.ts`, seeding is done at a request level, rather than a choice level. So if a request with `n > 1` is seeded, the choices would still have different results. But if two requests, both with `n > 1` and share the same seed, would generate identical results, across all choices. This is demonstrated in `examples/openai-api/src/seed.ts`, where we rigorously compare the strings generated.
Implementation wise, this is achieved with a customized implementation of linear congruential generator in TVMjs's runtime, since JS's `Math.random()` does not support seeding.
> [OpenAI] Support seed for reproducible generation

- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/logit-processor/package.json
- examples/openai-api/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
This version supports seeding generation, for more see:
- https://github.com/mlc-ai/web-llm/pull/335
On TVMjs side, we make the runtime seedable via:
- https://github.com/apache/tvm/pull/16722
> [Version] Bump version to 0.2.28

- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/logit-processor/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Two main changes in this new npm:
- `chatCompletion` now supports function calling: https://github.com/mlc-ai/web-llm/pull/321
- `Conversation` is revamped to support incoming updates of `mlc-chat-config.json` on HF: https://github.com/mlc-ai/web-llm/pull/339
- This change is backward compatible (i.e. works with both new and old `mlc-chat-config.json`)
- **Not forward compatible (i.e. when `mlc-chat-config.json` on HF is updated, you would have to update the npm to ^0.2.29)**
No change on TVMjs.
> [Version] Bump version to 0.2.29

- examples/logit-processor/src/logit_processor.ts
- src/chat_module.ts
- src/llm_chat.ts
- src/types.ts
- src/web_worker.ts
This PR supports SWA under PagedKVCache, and with this, now all models running on WebLLM will be compiled with PagedKVCache (rather than the old KVCache that is no longer maintained).
Hence, we removed codes in `llm_chat.ts` that were for backward compatibility. However, old wasms would still work with npm <= 0.2.29 since wasm versioning will be introduced with 0.2.30.
Note that API for `forwardTokensAndSample()` is changed since we no longer need `curPos`.
Relevant PRs:
- https://github.com/mlc-ai/mlc-llm/pull/1967
- https://github.com/apache/tvm/pull/16729
> [SWA] Support SWA in pagedKVCache, remove backward compatible code

- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/get-started-rest/package.json
- examples/get-started/package.json
- examples/logit-processor/package.json
- examples/openai-api/package.json
- examples/simple-chat/package.json
- examples/web-worker/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Changes include:
- Expose `prebuiltAppConfig` to include all prebuilt model libraries, so all prebuilt models can be accessed from the npm package
- Essentially the list of models in `gh-config.js` under `simple-chat`
- Add wasm versioning so 0.2.29 still works despite breaking changes in prebuilt model wasms
- For more see https://github.com/mlc-ai/web-llm/pull/355
- Support json mode in `chatCompletion()`
- For more see https://github.com/mlc-ai/web-llm/pull/350
- Update mistral models to use SWA with PagedKVCache, removed all backward compatibility code (since we now have wasm versioning)
- https://github.com/mlc-ai/web-llm/pull/351
Updated WASMs in https://github.com/mlc-ai/binary-mlc-llm-libs/tree/main/web-llm-models/v0_2_30
- If you'd like to compile your own WASMs that is …
> [Version] Bump version to 0.2.30

- examples/openai-api/src/openai_api.ts
- examples/web-worker/src/main.ts
- src/chat_module.ts
- src/conversation.ts
- src/llm_chat.ts
- src/openai_api_protocols/chat_completion.ts
- src/types.ts
- src/web_worker.ts
- tests/function_calling.test.ts
- tests/multi_round_chat.test.ts
- tests/openai_chat_completion.test.ts
We introduced the field `stateful` in `chatCompletion()` earlier to allow easier multi-round chatting in https://github.com/mlc-ai/web-llm/pull/330.
However, this is not ideal since we would prefer APIs that are functional in behavior, giving us various benefits (e.g. better fault tolerance for future use cases). 
Therefore, in this PR:
- We disable `chatCompletionRequest.stateful`, and ask users to maintain the chat history explicitly
- Instead, we introduce implicit KVCache reuse for multi-round chatting
- When we detect users are doing multi-round chatting, we will not reset the KV cache, so only the new message will be prefilled
- To detect multi-round chatting, we instantiate a `Conversation` instance for each request, and compare it with the current internal `Conversation`. If they …
> [KVCache] Add implicit KVCache reuse, disable stateful option for chatCompletion

- examples/chrome-extension-webgpu-service-worker/src/popup.ts
- examples/chrome-extension/src/popup.ts
- examples/get-started/src/get_started.ts
- examples/logit-processor/src/logit_processor.ts
- tests/function_calling.test.ts
Since we exposed all prebuilt links to `prebuiltAppConfig`, we update how examples select models correspondingly.
> [Examples] Update model link to reflect prebuilt changes

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/simple-chat/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- Enable `webllm.AppConfig.useIndexedDBCache` so that user can choose between the Cache API and IndexedDB Cache
- https://github.com/mlc-ai/web-llm/pull/352
- Refactor `ChatModule` to `Engine`, finalize OpenAI API to `engine.chat.completions.create()` to match that of OpenAI
- https://github.com/mlc-ai/web-llm/pull/361
- Add deprecation warning of `engine.generate()`, suggesting user to use `engine.chat.completions.create()`
- Subsequently, support implicit KVCache reuse for multi-round chat usage
- Though `chat.completions.create()` is functional, hence requiring users to maintain all chat history, we will reuse KVs if we detect multi-round chat, hence not sacrificing any performance
- See https://github.com/mlc-ai/web-llm/pull/359 and `examples/multi-round-chat`
WASMs are still …
> [Version] Bump version to 0.2.31

- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension-webgpu-service-worker/src/background.ts
- examples/chrome-extension-webgpu-service-worker/src/popup.ts
- package-lock.json
- package.json
- src/engine.ts
- src/index.ts
- src/message.ts
- src/service_worker.ts
- src/types.ts
- src/web_worker.ts
This PR adds ServiceWorkerEngine support. It wraps the `EngineInterface` and `EngineWorkerHandler` to use with Chrome's Service Worker, which comes in handy when building Chrome extensions.
Also update the chrome extension example to use the new ServiceWorkerEngine.
> Add ServiceWorkerEngine support. Migrate chrome extention example to use ServiceWorkerEngine

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/simple-chat/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- Add ServiceWorkerEngine support. Migrate chrome extension example to use ServiceWorkerEngine.
- https://github.com/mlc-ai/web-llm/pull/364
WASMs are still v0_2_30 as no compile-time changes are required. 
https://github.com/mlc-ai/relax/commit/c7bdcabd602f3d882e764232692d1d1eb449d07b
i.e. https://github.com/apache/tvm/commit/d1e24ca721d0c8110fab3e7db6b7375ebfeb8ac5
> [Version] Bump version to 0.2.32

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/simple-chat/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- Add Llama 3 Instruct models to `webllm.prebuiltAppConfig` 
- https://github.com/mlc-ai/web-llm/pull/368
WASMs are still v0_2_30 as no compile-time changes are required. 
- https://github.com/mlc-ai/relax/commit/d694451c580a931116a2c93571f21f7d791c7fa0
i.e. https://github.com/apache/tvm/commit/622bd150dd331780eb41a1c67c65aae802eb9b20
> [Version] Bump version to 0.2.33

- examples/simple-chat/src/simple_chat.ts
Instead of putting users' input as arguments to `insertAdjacentHTML()`, we use `insertAdjacentText` instead by creating a dedicated `appendUserMessage()` method.
> [SimpleChat] Treat user input as text rather than HTML

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/simple-chat/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- src/config.ts
- utils/vram_requirements/package.json
Main changes include:
- Support for JSON schema via https://github.com/mlc-ai/web-llm/pull/371
All WASMs are updated to `v0_2_34` reflect the change in MLC's runtime.
TVMjs compiled at https://github.com/apache/tvm/commit/57316dae1497c36ed57732a7a610018a990f1927
- Main change: https://github.com/apache/tvm/pull/16910
We updated all WASMs, as reflected by `modelVersion` in `src/config.ts` (reflected by the new folder `v0_2_34` in [binary-mlc-llm-libs](https://github.com/mlc-ai/binary-mlc-llm-libs/tree/main/web-llm-models)) and hence the implicitly updated `webllm.prebuiltAppConfig`. See https://github.com/mlc-ai/binary-mlc-llm-libs/pull/118 on the commits of MLC and TVM when compiling these models.
<0.2.34 users can still use WebLLM without breaking as we keep v0_2_30 models, and the links …
> [Version] Bump version to 0.2.34, update prebuilt WASM models

- site/index.md
- src/config.ts
Add `-1k` prebuilt for `llama-2-q4f32_1`. Reorder prebuilt models such that `-1k` models are defaulted in the demo page. Also add a note on `-1k` in demo site.
> [Prebuilt] Add 1k llama-2 q4f32_1 prebuilt

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/simple-chat/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Very minor change from 0.2.34, only slightly updated prebuilt config
- https://github.com/mlc-ai/web-llm/pull/377
`v0_2_34` as no change is required.
TVMjs compiled at https://github.com/apache/tvm/commit/57316dae1497c36ed57732a7a610018a990f1927
> [Version] Bump version to 0.2.35

- cleanup-index-js.sh
This PR post-processes web-llm's `index.js` by replacing all `new (require('u' + 'rl').URL)('file:' + __filename).href` with `"MLC_DUMMY_PATH"`:
```javascript
var _scriptDir = 
(typeof document === 'undefined' && typeof location === 'undefined' ? 
"MLC_DUMMY_PATH": 
typeof document === 'undefined' ? 
location.href : 
(document.currentScript && document.currentScript.src || new URL('index.js', document.baseURI).href)
);
```
which previously would raise error as shown in https://github.com/mlc-ai/web-llm/issues/383 and other issues.
Other occurrences of `"MLC_DUMMY_PATH"` are only in branches of `if (ENVIRONMENT_IS_NODE)` in runtime, which we do not consider / support as of now.
We use `"MLC_DUMMY_PATH"` instead of `null` because we do not expect the value to be used at all. If that is not …
> [Next][Fix] Remove require() in index.js for scriptDir

- README.md
- examples/service-worker/README.md
- examples/service-worker/package.json
- examples/service-worker/src/index.html
- examples/service-worker/src/main.ts
- examples/service-worker/src/sw.ts
- src/index.ts
- src/web_service_worker.ts
- src/web_worker.ts
This PR adds support for [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API). Unless the extension service worker currently in the repo that is used for Chrome extensions only, this is the generic service worker API that can be used for any web application.
To avoid change names of existing classes, I keep the original service worker file the same and named the new ones `WebServiceWorkerXXX`.
This PR also includes an example for running Web-LLM engine using Service Worker API and updates the README as well.
> Add Service Worker support and example

- src/service_worker.ts
- src/utils.ts
- src/web_service_worker.ts
Currently, even the client is initializing the worker engine with the exact same configurations, the worker will not correctly recognize this but instead it will unnecessarily re-initialize itself. The root cause is due to the use of `===` to compare object equity which is actually comparing object reference equity instead of value equity.
This PR fixed it by create utility functions for deep comparing the **VALUE** of these config objects. The code is tedious and thus I generated using AI models.
Tested on https://chat.neet.coffee with the following code added to `web_service_worker.ts`.
```typescript
console.log("modelId same? " + this.modelId === params.modelId);
console.log("chatOpts same? " + areChatOptionsEqual(this.chatOpts, params.chatOpts));
console.log("appConfig same? " + …
```
> [Fix] Avoid unnecessary engine reload by correctly comparing ChatOption and AppConfig objects

- src/message.ts
- src/service_worker.ts
- src/web_service_worker.ts
This PR adds heartbeat event in web service worker so that the client can monitor its status and respond correspondingly.
- Update `{ type: "keepAlive" }` event to `{ kind: "keepAlive" }` to keep all event format consistent
- Add heartbeat event in web service worker handler to report back its status
> [Function] Add heartbeat to service worker

- examples/service-worker/package.json
- examples/service-worker/src/main.ts
- package-lock.json
- package.json
- src/extension_service_worker.ts
- src/index.ts
- src/message.ts
- src/service_worker.ts
- src/web_worker.ts
- tsconfig.json
There are many different APIs available for the two-way communication between service worker and web pages. According to the suggestion of web.dev, previously we used the simple BroadcastChannel API.
https://web.dev/articles/two-way-communication-guide
However, if the service worker has been killed by the browser, messages sent via the BroadcastChannel API cannot revive it. This causes unstable service worker life while users are using the webapp.
This PR replaces BroadcastChannel API with the more primitive Client API as we found that messages sent via Client API will revive a stopped service worker. This ensures the normal functioning of our keep-alive mechanism.
- service_worker.ts:
- Replace `BroadcastChannel` with Client API  (`navigator.serviceWorker.controller.postMessage()` and …
> [Feature] Replace BroadcastChannel API with Client API in Service Worker

- cleanup-index-js.sh
Replace `import require$$3 from 'perf_hooks';` with `const require$$3 = "MLC_DUMMY_REQUIRE_VAR"` in `index.js`.
We use a dummy string because we should not reach to [this branch in tvmjs](https://github.com/apache/tvm/blob/a5862a5c696a3237f644f31bc312aae303213f3f/web/src/compact.ts#L29) which is for nodejs.
This should address https://github.com/mlc-ai/web-llm/issues/258 and https://github.com/mlc-ai/web-llm/issues/127
> [Fix] Remove perf hooks import from index.js

- src/engine.ts
Prior to this PR, when users `createEngine()` or call `reload()` with a model that is too large for the device, likely the device would keep generating, ignoring OOM issue and correctness. See https://github.com/mlc-ai/web-llm/issues/356 and https://github.com/mlc-ai/web-llm/issues/209. 
This PR catches such error with `device.lost.then()`, depending on tvmjs to call `device.destroy()` upon detecting error in `createBuffer()` via https://github.com/apache/tvm/pull/17005.
We have only observed `createBuffer()` errors and hence will only process such kind of errors for now. Besides, since most OOM errors occur in `reload()`, we make the error handling synchronous despite using `.then()` by throwing the error at the end of `reload()` if there is one.
> [Device] Catch WebGPU OOM error

- README.md
- examples/chrome-extension-webgpu-service-worker/src/background.ts
- examples/chrome-extension-webgpu-service-worker/src/popup.ts
- examples/service-worker/src/main.ts
- examples/service-worker/src/sw.ts
- src/index.ts
This PR renames the following classes in export to better align with their well-known names.
- WebServiceWorker -> ServiceWorker
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
- ServiceWorker -> ExtensionServiceWorker
https://developer.chrome.com/docs/extensions/develop/concepts/service-workers
Note, this is a **breaking** change for existing extension service worker engine users. Therefore, please merge with caution.
> [Rename] Rename service worker export classes

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
This version bump is breaking as we renamed APIs.
The only two changes are:
- Renamed all `Engine` to `MLCEngine`
- https://github.com/mlc-ai/web-llm/pull/408
- See https://github.com/mlc-ai/web-llm/pull/408/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80 fo the full list of changes
- To accommodate this breaking change, control-F `Engine` (with same capitalization) and replace with `MLCEngine` should suffice
- Renamed ServiceWorker classes:
- https://github.com/mlc-ai/web-llm/pull/403
- WebServiceWorker -> ServiceWorker
- ServiceWorker -> ExtensionServiceWorker
v0_2_34 as no change is required.
TVMjs compiled at https://github.com/apache/tvm/commit/a5862a5c696a3237f644f31bc312aae303213f3f, with no change
> [Version] Bump version to 0.2.37

- cleanup-index-js.sh
Address issue https://github.com/mlc-ai/web-llm/issues/414. Since `index.js.map` is a json, when specifying string, we should use `\"` instead of `"`.
Prior to this PR, we populate `const performanceNode = "MLC_DUMMY_REQUIRE_VAR"`, this PR changes it to `const performanceNode = \"MLC_DUMMY_REQUIRE_VAR\"`
> [Fix][Vite] Fix error for index.js.map

- .prettierrc
- src/service_worker.ts
Using service worker sometimes is tricky, especially when you are trying to debug an issue. This PR adds additional `debug` level logs for printing the entire event trace for easier debugging.
Broswer console in default logging level:
Broswer console in verbose logging level:
> [ServiceWorker] Add verbose mode for debugging

- src/message.ts
- src/service_worker.ts
This PR 
- refines the error message in service worker initialization to make it more user-friendly;
- resolves or suppresses ESLint warnings
> [ServiceWorker] Refine error message and fix lint warning

- src/engine.ts
This PR refines the error message if no WebGPU is available and unifies the message with TVM one.
https://github.com/apache/tvm/pull/17021
> [WebGPU] Refine no WebGPU error message

- package-lock.json
- package.json
- src/config.ts
- src/engine.ts
- src/extension_service_worker.ts
- src/index.ts
- src/llm_chat.ts
- src/service_worker.ts
- src/types.ts
- src/web_worker.ts
- utils/vram_requirements/src/vram_requirements.ts
This PR introduces a new package, `logLevel`, which is a lightweight logging javascript library for managing logging levels and filtering debug logs in production.
https://github.com/pimterry/loglevel
We exposed `logLevel` as part of the engine config to allow users to modify it. The default log level is `WARN`.
In `TRACE` level:
In `WARN` level:
> [Log] Set log level using 'loglevel' package

- examples/json-mode/src/json_mode.ts
- examples/json-schema/src/json_schema.ts
- src/config.ts
- src/grammar.ts
- src/llm_chat.ts
- src/support.ts
- tests/util.test.ts
This PR updates models to v0.2.39 compiled with https://github.com/mlc-ai/binary-mlc-llm-libs/pull/123
The main change is the new MLC-LLM runtime, which supports grammar (i.e. json mode) for Llama3.
- Hence we now read in field `tokenizer_info` (or deprecated `token_table_postproc_method`) from `mlc-chat-config.json` when post processing token table for Grammar
- If neither is available, we use the default `byte_fallback`
New prebuilt models introduced:
- Phi3-mini-4k
- Hermes-2-Pro-Llama-3-8B
- Qwen1.5-1.8B
- StableLM-2-zephyr_1.6B
Updates on examples:
- json-mode and json-schema now use Llama3 to demonstrate
- Function calling inside json-schema now uses `Hermes-2-Pro-Llama-3-8B` instead of `Hermes-2-Pro-Mistral`
> [Models] Add Phi3-mini, StableLM 1.6B, Qwen 1.8B, update MLC runtime

- README.md
- examples/cache-usage/src/cache_usage.ts
- examples/chrome-extension-webgpu-service-worker/src/popup.ts
- examples/chrome-extension/src/popup.ts
- examples/function-calling/src/function_calling.ts
- examples/get-started-web-worker/src/main.ts
- examples/get-started/src/get_started.ts
- examples/json-mode/src/json_mode.ts
- examples/json-schema/src/json_schema.ts
- examples/logit-processor/src/logit_processor.ts
- examples/logit-processor/src/worker.ts
- examples/multi-round-chat/src/multi_round_chat.ts
- examples/next-simple-chat/src/utils/chat_ui.ts
- examples/seed-to-reproduce/src/seed.ts
- examples/service-worker/src/main.ts
- examples/streaming/src/streaming.ts
- src/cache_util.ts
- src/config.ts
- src/engine.ts
- src/support.ts
- src/utils.ts
- tests/openai_chat_completion.test.ts
- tests/util.test.ts
- utils/vram_requirements/src/vram_requirements.ts
There are three changes to `ModelRecord` this PR brings:
We rename `modelId` in `webllm.prebuiltAppConfig` to be the exact same as the HF repo name. For most models, that means we simply append `-MLC` to the `modelId`. For the low-context version of the model, we would have `{HF-repo}-1k`, suggesting 1k context length.
As a result, we rename Phi2 and phi1.5 models since their `modelId` did not match with the repo name
- `Phi2-q4f32_1` → `phi-2-q4f32_1-MLC`
- `Phi1.5-q4f16_1` → `phi-1_5-q4f16_1-MLC`
To better match with other platforms of MLC-LLM (e.g. iOS, Android), we rename the `ModelRecord` fields.
Instead of `"https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC/resolve/main/"`, we now make it `"https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC/"`; note the …
> [Config] Enhance ModelRecord

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Main changes include:
- New prebuilt models:
- Phi3-mini
- StableLM-2-zephyr-1.6B
- Qwen1.5-1.8B
- Hermes2-Pro-Llama-3-8B to prebuilt models
- Updates on `ModelRecord` fields
- For detail see: https://github.com/mlc-ai/web-llm/pull/435
- Update all WASMs
- For detail see: https://github.com/mlc-ai/web-llm/pull/433
- Update all WASMs to v0.2.39
- Support grammar for Llama3, hence update examples/json-mode to use `Llama3` and `Hermes2-pro-Llama3-8B` for function calling in `examples/json-schema`
- Use `loglevel` package:
- For details see https://github.com/mlc-ai/web-llm/pull/427
- Fix `index.js.map` issue for Vite
- https://github.com/mlc-ai/web-llm/pull/420
- Enhance error handling and ServiceWorker
TVMjs compiled at https://github.com/apache/tvm/commit/71f7af7985e2c883494a9aa80e0f5d12c15 …
> [Version] Bump version to 0.2.39, update prebuilt WASMs

- src/config.ts
Follow up from #427 to prevent the following type issue introduced on `v0.2.39`:
This issue fails type-checking [[reference](https://github.com/felladrin/MiniSearch/actions/runs/9298738476/job/25591213310?pr=356)] and forces users to define the `logLevel` config.
But in fact, `logLevel` already has a default value and was intended to be an optional parameter.
This PR fixes it.
> Set `MLCEngineConfig.logLevel` optional in `config.ts`

- cleanup-index-js.sh
This PR fixes `\"` issue in `index.js.map`, which breaks Vite deployment, follows the thread https://github.com/mlc-ai/web-llm/issues/414
This PR undoes the change in `cleanup-index-js.sh` to `index.js` in https://github.com/mlc-ai/web-llm/pull/420, and update `"` to `'` for `index.js.map`.
> [Fix][Vite] Fix string escape in index.js.map

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
This patch contains various small fixes:
- Allow `log` from `engine.ts` and `llm_chat.ts`, etc. to show in service and web worker
- https://github.com/mlc-ai/web-llm/commit/e720f2ab3492dbb94fb76f3741edf2f493cd063c
- Fix `index.js.map` issue for Vite
- https://github.com/mlc-ai/web-llm/pull/440
- Make `MLCEngineConfig.logLevel` optional
- https://github.com/mlc-ai/web-llm/pull/439
No change, TVMjs compiled at https://github.com/apache/tvm/commit/71f7af7985e2c883494a9aa80e0f5d12c154a990
- No change -- 0.2.39
> [Version] Bump version to 0.2.40

- src/config.ts
- src/support.ts
- tests/util.test.ts
This is a small change to `cleanModelUrl` to allow for more flexibility and backwards compatibility in the modelUrl. The function will now only append "resolve/main/" if the provided URL does not already contain "resolve". Tested with the following URL formats to ensure that all work.
- https://huggingface.co/USER/MODEL
- https://huggingface.co/USER/MODEL/
- https://huggingface.co/USER/MODEL/resolve/branch
- https://huggingface.co/USER/MODEL/resolve/branch/
> Update cleanModelUrl to support non-main branches

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- Support function calling with `Hermes-2-Pro` models with `ChatCompletionRequest.tools` (see `examples/function-calling` for usage)
- https://github.com/mlc-ai/web-llm/pull/451
No change, TVMjs compiled at https://github.com/apache/tvm/commit/71f7af7985e2c883494a9aa80e0f5d12c154a990
- No change -- 0.2.39
> [Version] Bump version to 0.2.41

- src/engine.ts
Trivial fix. Fix how we condition on `isFunctionCalling` when populating messages for non-streaming cases, so that non-function calling request would not have an undefined `tool_calls` field.
> [Fix] Small fix on tool_calls

- src/engine.ts
This PR is a tiny one, updating the signature of getToolCallFromOutputMessage() function to overload it so that TypeScript can correctly inference the retrun type based on parameter automatically.
> [type] Add signature for overloading getToolCallFromOutputMessage()

- examples/get-started/src/get_started.ts
- src/config.ts
- src/engine.ts
- src/llm_chat.ts
There are three KVCache-related fields: `context_window_size`, `sliding_window_size`, and `attention_sink_size`.
Prior to this PR, we read these three fields from the WASM, because a while back these affect the model's compilation. Now these things can be changed in runtime, so we read these in from `mlc-chat-config.json`.
Thus, we add these three fields into `ChatConfig`, hence `ChatOptions`, so users can override these in `reload()`.
Alternatively, users can override these in `ModelRecord.overrides` (i.e. a "default override"). As a result, we no longer need both `ctx4k.wasm` and `ctx1k.wasm`; instead we simply add `overrides: {context_window_size: 1024}` in the model record for the `-1k` models and share the same wasm.
We first override with `overrides`, then with `chatOpts` (i.e. …
> [KVCache] Add KVCache settings to ChatOptions, add overrides to ModelRecord

- package-lock.json
- package.json
- src/config.ts
Add new models:
- `Mistral-7B-Instruct-v0.3-q4f16_1-MLC` (we had v0.2 before)
- `Mistral-7B-Instruct-v0.3-q4f32_1-MLC`
- `TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC` (we had v0.4 before)
- `TinyLlama-1.1B-Chat-v1.0-q4f32_1-MLC` (we had v0.4 before)
To support Mistral v0.3, we also bump web-tokenizers to 0.1.4
Note: Mistral v0.3's WASM should be identical to v0.2; hence we can use it for models like Mistral v0.2, OpenHermes, WizardMath, etc.
> [Models] Add Mistral v0.3 and TinyLlama v1.0; bump web-tokenizer version

- README.md
- examples/function-calling/src/function_calling.ts
- examples/get-started-web-worker/src/main.ts
- examples/get-started/src/get_started.ts
- examples/json-mode/src/json_mode.ts
- examples/json-schema/src/json_schema.ts
- examples/multi-round-chat/src/multi_round_chat.ts
- examples/seed-to-reproduce/src/seed.ts
- examples/service-worker/src/main.ts
- examples/streaming/src/streaming.ts
- src/engine.ts
- src/llm_chat.ts
- src/openai_api_protocols/chat_completion.ts
- tests/openai_chat_completion.test.ts
This change is not breaking. Behavior only changes when `stream_options: {include_usage: True}` is set for streaming, during which we yield another chunk with empty `choices` after the last chunk. 
Also include `prefill_tokens_per_s` and `decode_tokens_per_s` for `usage` in both streaming and non-streaming, hence replacing the previous usage of `runtimeStatsText()`.
> [OpenAI] Add include_usage in streaming, add prefill decode speed to usage

- examples/get-started-web-worker/src/main.ts
- examples/get-started/src/get_started.ts
- examples/json-mode/src/json_mode.ts
- examples/json-schema/src/json_schema.ts
- examples/seed-to-reproduce/src/seed.ts
- examples/service-worker/src/main.ts
- src/config.ts
- src/engine.ts
- src/llm_chat.ts
- src/openai_api_protocols/chat_completion.ts
- src/utils.ts
- tests/generation_config.test.ts
- tests/openai_chat_completion.test.ts
- **[Breaking]** Rename `max_gen_len` to `max_tokens` in `ChatCompletionRequest`
- Remove reading `max_gen_len` from `mlc-chat-config.json`, hence remove it from `ChatOptions`
- Remove reading `mean_gen_len` and `shift_fill_factor` from `mlc-chat-config.json`, hence:
- Remove these two fields from `ChatOption`
- Throw error when the input prompt tokens exceed `context_window_size`, prompting user to truncate input, or increase `context_window_size`, or use sliding window
- Finish reason with `length` when decoding exceed `context_window_size` (when `prompt_size + max_tokens > context_window_size`)
- Hence this error is never shown to user: https://github.com/mlc-ai/web-llm/issues/385
This change is needed in order to be compatible with new `mlc-chat-config.json` in hugginface due to …
> [OpenAI] Handle exceeding context window size, rename max_gen_len to max_tokens

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- New models:
- Mistral-7B-Instruct-v0.3-q4f16_1-MLC (we had v0.2 before)
- Mistral-7B-Instruct-v0.3-q4f32_1-MLC
- TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC (we had v0.4 before)
- TinyLlama-1.1B-Chat-v1.0-q4f32_1-MLC (we had v0.4 before)
- https://github.com/mlc-ai/web-llm/pull/457
- **[Breaking] renamed `max_gen_len` to `max_tokens` in ChatCompletionRequest**
- Remove usage of `mean_gen_len` and `shift_fill_factor`, throw error when request's prompt exceed contextWindowSize
- Terminate generation with `"length"` stop reason when decoding exceed contextWindowSize
- https://github.com/mlc-ai/web-llm/pull/456
- Add `include_usage` in streaming, add prefill/decode speed to `usage` to replace `runtimeStatsText()`
- https://github.com/mlc-ai/web-llm/pull/455
- Allow overriding KVCache settings via …
> [Version] Bump version to 0.2.42

- examples/next-simple-chat/src/utils/chat_ui.ts
- examples/simple-chat-js/index.js
- examples/simple-chat-ts/src/simple_chat.ts
- examples/simple-chat-upload/src/simple_chat.ts
- src/engine.ts
Recently we added `usage` to the last chunk in streaming if the user specifies `streamOptions: { include_usage: True}` in the request, to be compatible with the latest OpenAI API; for more see https://github.com/mlc-ai/web-llm/pull/456.
This PR updates our streaming examples to use `chunk.usage` instead of `runtimeStatsText()`. It is expected that we will deprecate `runtimeStatsText()` in the future. Currently, only low-level API `forwardTokenAndSample()` still needs it as they do not use OpenAI API (e.g. `examples/logit-processor`).
Such examples include:
- simple-chat-ts
- simple-chat-js
- next-simple-chat
- streaming (already updated)
> [Streaming] Replace runtimeStatsText() with usage in examples

- src/config.ts
- src/conversation.ts
- src/grammar.ts
- src/llm_chat.ts
- tests/conv_template.test.ts
This PR adds QWen2 0.5B, 1.5B, and 7B, hence deprecating Qwen1.5-1.8B
This PR also updates the model wasm version to 0.2.43 due to recent changes in MLC's renaming of TVM global function. As a result, we update how `grammar.ts` gets the global function.
Additionally, we remove 
```typescript
if (system_prompt) {
system_prompt += this.config.seps[0];
}
```
to reflect the up-to-date conv template in `mlc-chat-config.json`.
> [Model] Support Qwen2 0.5B, 1.5B, 7B, bump wasm version to 0.2.43

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- New models:
- Qwen2 0.5B, 1.5B, 7B via https://github.com/mlc-ai/web-llm/pull/463
- Add deprecation warning for `runtimeStatsText()` and suggest using `.usage` 
- https://github.com/mlc-ai/web-llm/pull/460
- Do not use sliding window for mistral models by default, but still can be overridden by user
- https://github.com/mlc-ai/web-llm/pull/461
Updated to https://github.com/mlc-ai/binary-mlc-llm-libs/pull/126 for trivial rename changes in MLC's WASM runtime.
Compiled at https://github.com/apache/tvm/commit/5d077c5a0900a6b98934b9e9d813da14ba0fc24b with no changes
> [Version] Bump version to 0.2.43

- README.md
- examples/cache-usage/src/cache_usage.ts
- examples/chrome-extension-webgpu-service-worker/src/background.ts
- examples/get-started/src/get_started.ts
- examples/multi-round-chat/src/multi_round_chat.ts
- examples/service-worker/src/sw.ts
- examples/simple-chat-ts/src/simple_chat.ts
- examples/simple-chat-upload/src/simple_chat.ts
- src/config.ts
- src/engine.ts
- src/extension_service_worker.ts
- src/index.ts
- src/message.ts
- src/service_worker.ts
- src/types.ts
- src/web_worker.ts
- `reload(selectedModel, chatOpts?, appConfig?)` --> `reload(selectedModel, chatOpts?)`
- Add `setAppConfig()` as `appConfig` is now a field of `MLCEngine`
- `new MLCEngine()` --> `new MLCEngine(engineConfig?)`
- Remove `chatOpts` from `EngineConfig`, add it to `CreateMLCEngine()` args separately
- Corresponding changes in WebWorker and ServiceWorker
- `ServiceWorkerMLCEngineHandler` --> `MLCEngineServiceWorkerHandler`
- Remove `init()` in `ServiceWorkerMLCEngine`
The motivation is to separate the creation of an engine (sync, instant, like an endpoint), and loading a model (async, can take long). This PR consolidates `MLCEngine` initialization, hence affecting WebWorker and ServiceWorker as well.
After this PR, there are two equivalent ways to create an engine:
```typescript
const engine …
```
> [API][Breaking] Consolidate Engine constructor, CreateMLCEngine, reload()

- README.md
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
This version bump has breaking changes to the API, mainly:
- `reload(selectedModel, chatOpts?, appConfig?)` --> `reload(selectedModel, chatOpts?)`
- Add `setAppConfig()`, as `appConfig` is now a field of `MLCEngine`
- `new MLCEngine()` --> `new MLCEngine(engineConfig?)`
- Remove `chatOpts` from `EngineConfig`, add it to `CreateMLCEngine()` args separately
- Corresponding changes in WebWorker and ServiceWorker
- `ServiceWorkerMLCEngineHandler` --> `MLCEngineServiceWorkerHandler`
- Remove `init()` in `ServiceWorkerMLCEngine`
For more, see:
- https://github.com/mlc-ai/web-llm/pull/466
> [Version][Breaking] Bump version to 0.2.44

- src/extension_service_worker.ts
- src/message.ts
- src/service_worker.ts
- src/web_worker.ts
Service worker may be killed by the browser despite us sending `keepAlive` messages. Upon killed, all states in the worker thread is lost. When the frontend sends another request, expecting the model loaded, the backend MLCEngine throws an error, essentially due to the mismatch of frontend's expectation and backend's reality.
This PR adds `modelId` and `chatOpts` to `WebWorkerMLCEngine` (hence ServiceWorker and ExtensionServiceWorker), with the semantics being: the model and config that the frontend expects the backend to be currently loaded with. When sending a request, we send the expectation as well.
For backend, upon receiving the chat completion request, it compares the expectation with its current state. If not matched (due to service worker killed), we reload before carrying out …
> [ServiceWorker] Reload model when service worker killed

- README.md
- examples/chrome-extension-webgpu-service-worker/src/background.ts
- examples/get-started-web-worker/src/worker.ts
- examples/logit-processor/src/worker.ts
- examples/service-worker/src/sw.ts
- examples/simple-chat-ts/src/worker.ts
- examples/simple-chat-upload/src/worker.ts
- src/extension_service_worker.ts
- src/index.ts
- src/service_worker.ts
- src/web_worker.ts
This PR applies to all `WebWorkerMLCEngine`, `ServiceWorkerMLCEngine`, and `ExtensionServiceWorkerMLCEngine`.
Prior to this PR, the worker thread script looked like the following:
```typescript
import {
MLCEngineServiceWorkerHandler,
MLCEngine,
} from "@mlc-ai/web-llm";
const engine = new MLCEngine();
let handler: MLCEngineServiceWorkerHandler;
self.addEventListener("activate", function (event) {
handler = new MLCEngineServiceWorkerHandler(engine);
console.log("Service Worker is ready");
});
```
This may confuse users because they need to instantiate an `MLCEngine` in the backend, and an `ServiceWorkerMLCEngine` in the frontend. After this PR, the script looks like the following:
```typescript
import { ServiceWorkerMLCEngineHandler } from "@mlc-ai/web-llm";
let handler: …
```
> [WorkerHandler][Breaking] Create MLCEngine in worker handler internally

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
This version bump has breaking changes to the API, mainly:
- Rename of Handler:
- `MLCEngineWorkerHandler` --> `WebWorkerMLCEngineHandler`
- `MLCEngineServiceWorkerHandler` --> `ServiceWorkerMLCEngineHandler`
- `MLCEngineExtensionServiceWorkerHandler` --> `ExtensionServiceWorkerMLCEngineHandler`
- In worker script, instantiate `MLCEngine()` in the handler constructor internally
- For more, see https://github.com/mlc-ai/web-llm/pull/472
Besides, we handle the case when service worker is killed unexpectedly, so that upon the next request, we help the backend engine reload. 
- For more, see https://github.com/mlc-ai/web-llm/pull/471
No change, still v0.2.43.
No change, compiled at https://github.com/apache/tvm/commit/5d077c5a0900a6b98934b9e9d813da14ba0fc24b
> [Version][Breaking] Bump version to 0.2.45

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Exactly the same as 0.2.45 except fixing wrong wasm link for prebuilt model:
`RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC-1k` and `RedPajama-INCITE-Chat-3B-v1-q4f32_1-MLC-1k`
> [Version][Trivial] Bump version to 0.2.46

- src/web_worker.ts
In 7e11cf3f3a0cb1e295003e180ae15dee2329a5eb, we change the worker handler API to hide the engine creation internally. However, this also restricts the user's ability to directly operate the engine on the worker script for advanced use cases like eager loading (https://github.com/mlc-ai/web-llm/issues/469#issuecomment-2168470922).
Therefore, this PR exposes the `handler.engine` as a public property so users could directly operate it if they need.
Eg. They can do `handler.engine.reload()` to directly trigger a model load.
> [Worker] Expose handler.engine as public property

- src/config.ts
Add quantized(q4f16) qwen2-0.5b to the list of supported models. [PR](https://github.com/mlc-ai/binary-mlc-llm-libs/pull/128) must be merged before merging this.
> Add quantized qwen2-0.5b

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Exactly the same as 0.2.46 except we update TVMjs to https://github.com/apache/tvm/commit/32e9a48b1fbc78a58447f392f2530c98553eb3dc.
The main change is that, when requesting a WebGPU device, we may fall back `maxBufferSize` to the default 256MB when 1GB is too much for the device. This is motivated by iOS support on Safari, tested on iOS 18 Developer Beta. Fore more, see:
- https://github.com/apache/tvm/pull/17150
No change, still v0.2.43.
Updated, compiled at https://github.com/apache/tvm/commit/32e9a48b1fbc78a58447f392f2530c98553eb3dc
> [Version][Trivial] Bump version to 0.2.47

- src/config.ts
- src/grammar.ts
- src/llm_chat.ts
- src/support.ts
Before this PR, we may run into issues like the following when using json mode with Phi3:
```
index.js:1913 [FATAL] /Users/cfruan/Documents/mlc-llm/cpp/grammar/grammar_state_matcher.cc:202:
Check failed: (token_id >= 0 && token_id < init_ctx_->vocab_size) is false: Invalid token id 32042 for GrammarStateMatcher
```
This PR fixes this issue for models like Phi3, where the `vocab_size` in `config.json` may be larger than vocabs recorded in `tokenizer.json`. For more see:
- https://github.com/mlc-ai/mlc-llm/pull/2651
As a result, we had to recompile all WASMs, hence updating the wasm version to v0_2_48:
- https://github.com/mlc-ai/binary-mlc-llm-libs/pull/129
To support this in runtime, `ChatConfig` adds a new field `vocab_size` read from `mlc-chat-config.json` and update the signature of …
> [WASM][Fix] Fix json mode for phi3, bump to v0_2_48 wasm

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- tests/generation_config.test.ts
- tests/openai_chat_completion.test.ts
- utils/vram_requirements/package.json
- Fixed potential error in json mode for some models like Phi3 and Qwen2; for more see
- https://github.com/mlc-ai/web-llm/pull/501
Due to the fix, updated WASMs to `v0_2_48`
- https://github.com/mlc-ai/binary-mlc-llm-libs/pull/129
No change, compiled at https://github.com/apache/tvm/commit/32e9a48b1fbc78a58447f392f2530c98553eb3dc
> [Version][Trivial] Bump version to 0.2.48

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Only change is the addition of SmolLM to preset model list: https://github.com/mlc-ai/web-llm/pull/508
No change, compiled at https://github.com/apache/tvm/commit/32e9a48b1fbc78a58447f392f2530c98553eb3dc
0.2.49 skipped due to a mistake.
> [Version] Bump version to 0.2.50

- README.md
- examples/get-started-web-worker/src/main.ts
- examples/get-started/src/get_started.ts
- examples/json-mode/src/json_mode.ts
- examples/json-schema/src/json_schema.ts
- examples/multi-round-chat/src/multi_round_chat.ts
- examples/next-simple-chat/src/utils/chat_ui.ts
- examples/seed-to-reproduce/src/seed.ts
- examples/service-worker/src/main.ts
- examples/simple-chat-js/index.js
- examples/streaming/src/streaming.ts
- src/config.ts
- src/engine.ts
- tests/openai_chat_completion.test.ts
Add Llama3.1 8B and 70B to prebuilt models. Update examples from Llama3 to Llama3.1 Llama 3 models are still kept.
Related PRs:
- https://github.com/mlc-ai/binary-mlc-llm-libs/pull/131
- https://github.com/mlc-ai/mlc-llm/pull/2682
> [Model] Add Llama 3.1 to prebuilt models

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
The only difference is that we added Llama3.1 models (still kept Llama3 models):
- https://github.com/mlc-ai/web-llm/pull/513
No change, compiled at https://github.com/apache/tvm/commit/e6476847753c80e054719ac47bc2091c888418b6
> [Version] Bump version to 0.2.51

- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
The only difference is that we added Gemma 2 models (still kept Gemma models):
- https://github.com/mlc-ai/web-llm/pull/520
TVMjs
No change, compiled at https://github.com/apache/tvm/commit/e6476847753c80e054719ac47bc2091c888418b6
> [Version] Bump version to 0.2.52

- examples/abort-reload/README.md
- examples/abort-reload/package.json
- examples/abort-reload/src/get_started.html
- examples/abort-reload/src/get_started.js
- src/engine.ts
- src/llm_chat.ts
This PR updates the engine `reload()` and `unload()` methods to allow users to abort an uncompleted `reload()` by either:
- call `unload()` any time before `reload()` completed
- call `reload()` again before the previous `reload()` completed
Example added in `examples/abort-reload`.
Console output:
```
Start to fetch params
get_started.js:16 Fetching param cache[0/108]: 28MB fetched. 0% completed, 1 secs elapsed. It can take a while when we first visit this page to populate the cache. Later refreshes will become faster.
get_started.js:28 calling unload
engine.ts:154 Reload() is aborted. Failed to execute 'add' on 'Cache': Cache.add() was aborted
```
Related issues:
https://github.com/mlc-ai/web-llm/issues/484
https://github.com/mlc-ai/web-llm/issues/499
Previously, we had an issue where a …
> [Engine] Allow manually aborting reload, fix unexpected deviceLostError

- src/config.ts
Add Qwen2-Math models to model preset, reusing WASM of Qwen2. Specifically, we add:
- `"Qwen2-Math-1.5B-Instruct-q4f16_1-MLC"`
- `"Qwen2-Math-1.5B-Instruct-q4f32_1-MLC"`
- `"Qwen2-Math-7B-Instruct-q4f16_1-MLC"`
- `"Qwen2-Math-7B-Instruct-q4f32_1-MLC"`
> [Model] Add Qwen2 math 1.5B and 7B

- src/extension_service_worker.ts
- src/service_worker.ts
- src/web_worker.ts
In https://github.com/mlc-ai/web-llm/pull/471, we add `modelId` and `chatOpts` to `ServiceWorkerMLCEngineHandler ` and `ExtensionServiceWorkerMLCEngineHandler`. The motivation was to reload the model once the handler detects an out-of-sync between what the frontend engine expects versus what the low-level engine is loaded with. This out-of-sync usually happens when a service worker is killed unexpectedly.
Recently, it is observed that such out-of-sync can happen in web worker as well. Therefore, we move the logic to `WebWorkerMLCEngineHandler`. The aforementioned handlers calls `super.onmessage()` at the end, so no change in behavior is expected from them.
Tested in WebLLMChat, intentionally terminating service worker and sending another message trigger the same behavior as before.
> [Worker] Move reload upon worker termination to WebWorker

- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- Add API `engine.completions()` in addition to `engine.chat.completions()`:
- https://github.com/mlc-ai/web-llm/pull/534
- Reload model when web worker terminated (in addition to service worker):
- https://github.com/mlc-ai/web-llm/pull/533
- Still compiled at https://github.com/apache/tvm/commit/1fcb62023f0a5f878abd5b43ec9e547933fb5fab, no change
> [Version] Bump version to 0.2.56

- src/cache_util.ts
- src/engine.ts
- src/support.ts
- src/types.ts
This PR reorganizes `engine.ts` to keep it relatively more organized.
- We move `getToolCallFromOutputMessage()` from `engine.ts` to `support.ts` since it does not depend on any engine-related fields and is stateless
- We move `asyncLoadTokenizer()` from `engine.ts` to `cache_util.ts` for the same reason
- In future, we can implement a common helper for `chatCompletion()` and `completion()`
- For `engine.ts`, we break down the functions into sections:
0. Setters and getters
1. Model/pipeline loading and unloading: `reload()`, `unload()`
2. Underlying auto-regressive generation functions: `_generate()`, `asyncGenerate()`, `interruptGenerate()`
3. High-level generation APIs: `generate()` (deprecated), `chatCompletion()`, `completion()`
4. WebGPU info-querying helpers. Arguably, this can be …
> [Chore] Reorganize engine.ts

- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- Supports embedding via OpenAI API `engine.embeddings.create()`:
- https://github.com/mlc-ai/web-llm/pull/538
- Currently, only `snowflake-arctic-embed-s` and `snowflake-arctic-embed-m` are supported. We add the following models to the prebuilt model list:
- `snowflake-arctic-embed-m-q0f32-MLC-b32`
- `snowflake-arctic-embed-m-q0f32-MLC-b4`
- `snowflake-arctic-embed-s-q0f32-MLC-b32`
- `snowflake-arctic-embed-s-q0f32-MLC-b4`
- `b32` means the model is compiled to support a maximum batch size of 32. If an input with more than 32 entries are provided, we will call multiple `forward()` (e.g. if input has 67 entries, we forward 3 times). The larger the maximum batch size, the more memory it takes to load the model. See `ModelRecord.vram_required_MB` in `config.ts` for specifics.
Still compiled …
> [Version] Bump version to 0.2.58, support embedding

- src/engine.ts
- src/message.ts
- src/types.ts
- src/web_worker.ts
This PR deprecates `generate()` from all `MLCEngineInterface`. Its usage can be completely covered by `engine.chat.completions()` for conversation-style generation, and `engine.completions()` for raw text completion. 
Specifically for using the above two OpenAI APIs for multi-round chat with KV reuse, see `examples/multi-round-chat`.
We deprecate this because future changes on the engine (e.g. allowing multiple models to be loaded in engine) would break this `generate()` API and require extra effort to maintain.
Tested with streaming/non-streaming on MLCEngine/WebWorkerMLCEngine to ensure other APIs are not affected.
> [API] Deprecate engine.generate()

- examples/README.md
- examples/multi-models/README.md
- examples/multi-models/package.json
- examples/multi-models/src/multi_models.html
- examples/multi-models/src/multi_models.ts
- src/embedding.ts
- src/engine.ts
- src/error.ts
- src/extension_service_worker.ts
- src/message.ts
- src/openai_api_protocols/chat_completion.ts
- src/openai_api_protocols/completion.ts
- src/openai_api_protocols/embedding.ts
- src/service_worker.ts
- src/support.ts
- src/types.ts
- src/utils.ts
- src/web_worker.ts
- tests/openai_chat_completion.test.ts
- tests/openai_completion.test.ts
- tests/openai_embeddings.test.ts
- tests/util.test.ts
This PR does not change any behavior of existingly supported API/workflow, but only introduces new behaviors when multiple models are loaded in a single engine. For users, please refer to `examples/multi-models` and "User-facing changes" below.
```typescript
const selectedModel1 = "Phi-3-mini-4k-instruct-q4f32_1-MLC-1k";
const selectedModel2 = "gemma-2-2b-it-q4f32_1-MLC-1k";
const engine: webllm.MLCEngineInterface = await webllm.CreateMLCEngine(
[selectedModel1, selectedModel2],
);
```
- When multiple models are loaded in the engine:
- `model` field is required to be specified in `ChatCompletionRequest`, `EmbeddingCreateParams`, and `CompletionCreateParams`
- The following engine APIs need to specify the target model: `getMessage()`, `runtimeStatsText()`, `resetChat()`, …
> [API][Engine] Support loading multiple models in a single engine

- examples/multi-models/src/main.ts
- examples/multi-models/src/multi_models.html
- examples/multi-models/src/multi_models.ts
- examples/multi-models/src/worker.ts
- src/message.ts
- src/web_worker.ts
This is a follow-up to https://github.com/mlc-ai/web-llm/pull/542. Update `examples/multi-model` to use web worker, and to also show case generating responses from two models concurrently from the same engine. This is already supported for `MLCEngine` prior to this PR, but `WebWorkerMLCEngine` needed a patch. Specifically:
- Prior to this PR, `WebWorkerMLCEngineHandler` maintains a single `asyncGenreator`, assuming there is only one model.
- Now, to support concurrent streaming request, we replace `this.asyncGenerator` with `this.loadedModelIdToAsyncGenerator`, which maps from a model id to its dedicated `asyncGenerator`
- As a result, messages related to streaming need to specify the `selectedModelId`, hence the updates for the message sending and handling of `chatCompletionStreamInit`, …
> [Fix] Allow concurrent inference for multi model in WebWorker

- src/engine.ts
- src/error.ts
This PR reorganizes internal code a bit to reuse code. We rename internal helper method `getLLMStates()` to `getModelStates()` and add `getEmebeddingStates()`, so engine's methods `embedding()`, `completion()`, and `chatCompletion()` can share the same preprocessing helper method.
> [Trivial] Generalize getModelStates

- examples/README.md
- examples/embeddings/src/embeddings.ts
Add a simple example of RAG using Langchain.js, following [its cookbook](https://js.langchain.com/v0.1/docs/expression_language/cookbook/retrieval/).
We use WebLLM for both embedding and LLM, within a single engine. There are many possible ways to achieve RAG (e.g. degree of integration with Langchain, using WebWorker, etc.). We only provide a minimal example here.
> [RAG] Add example for RAG with Langchain.js

- examples/multi-models/src/main.ts
- src/engine.ts
- src/support.ts
- src/types.ts
- tests/util.test.ts
A model cannot handle > 1 concurrent request (e.g. >1 calls to `chat.completions.create()`) since we do not support continuous batching, and each request requires its own resources such as the KV cache. (Though "concurrent" requests to different models in the same engine is supported)
As a result, as pointed out in https://github.com/mlc-ai/web-llm/issues/522, when users try something like the following code:
```typescript
const engine = await CreateMLCEngine("Phi-3-mini-4k-instruct-q4f16_1-MLC")
async function sendRequest() {
const reply = await engine.chat.completions.create({
messages: [{ role: "user", content: "Hello!" }],
max_tokens: 64,
});
console.log(reply.choices[0].message.content);
}
await Promise.all([sendRequest(), sendRequest()]);
```
the model's state and the generation …
> [Fix] Implement lock to ensure FCFS of requests to same model

- examples/multi-models/src/main.ts
- src/config.ts
This PR adds the newly release Phi3.5-mini, adding the following `model_id`s to our prebuilt model list:
- `Phi-3.5-mini-instruct-q4f16_1-MLC` (4k KVCache)
- `Phi-3.5-mini-instruct-q4f32_1-MLC` (4k KVCache)
- `Phi-3.5-mini-instruct-q4f16_1-MLC-1k` (1k KVCache)
- `Phi-3.5-mini-instruct-q4f16_1-MLC-1k` (1k KVCache)
See https://github.com/mlc-ai/binary-mlc-llm-libs/pull/136 for on which commits of TVM and MLC-LLM this is compiled with.
Note that Phi-3.5-mini comes with support up to 128K context (unlike Phi-3-mini which only has 4k) thanks to rope scaling which MLC-LLM supports, which you can take advantage of in WebLLM by increasing `ModelRecord.overrides.context_window_size` or specifying it in `ChatOptions` when loading a model, as long as there is enough VRAM.
> [Model] Add Phi3.5-mini

- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- https://github.com/mlc-ai/web-llm/pull/555
- Updated to current head: https://github.com/apache/tvm/commit/15180082626d01ccad0648a088d11a29e0678790
- Main change is https://github.com/apache/tvm/pull/17251
- This is needed for WASMs compiled after https://github.com/apache/tvm/pull/17257 is merged (e.g. Phi-3.5). TVM global functions that returns bool need this PR to run correctly (e.g. `AcceptToken()` in BNFGrammar) in runtime.
- However, these are backward compatible to WASMs compiled prior to this PR. Tested with Phi-3 (old WASM) running grammar.
> [Version] Bump version to 0.2.62

- src/config.ts
Added Hermes 3 (q4f16_1 and q4f32_1) to WebLLM.
> added hermes 3

- src/config.ts
This PR adds the following models to prebuilt list:
- Qwen2.5-0.5B - `q0f16`, `q0f32`, `q4f16_1`, `q4f32_1`
- Qwen2.5-1.5B, 3B, 7B - `q4f16_1`, `q4f32_1`
- Qwen2.5-Coder-1.5B, 7B - `q4f16_1`, `q4f32_1`
Previous Qwen2 models are not deprecated.
All models reuse previous Qwen2 WASMs (except Qwen2.5-3B since Qwen2 does not have a 3B variant, which we compile at head with https://github.com/mlc-ai/binary-mlc-llm-libs/pull/139)
> [Model] Support Qwen2.5 Instruct and Coder

- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
This new version only introduces new models:
- https://github.com/mlc-ai/web-llm/pull/558
- Adds `Hermes-3-Llama-3.1-8B-q4f32_1-MLC` and `Hermes-3-Llama-3.1-8B-q4f16_1-MLC` to the prebuilt
- https://github.com/mlc-ai/web-llm/pull/564
- Add the following models to prebuilt:
- Qwen2.5-0.5B - q0f16, q0f32, q4f16_1, q4f32_1
- Qwen2.5-1.5B, 3B, 7B - q4f16_1, q4f32_1
- Qwen2.5-Coder-1.5B, 7B - q4f16_1, q4f32_1
- Updated to current head: https://github.com/apache/tvm/commit/a24204640efe3dcf519ca3388633a8a62a7600eb
- Main change is https://github.com/apache/tvm/pull/17371; without it, it prevents us from installing dependencies when building web-llm
> [Version] Bump version to 0.2.63

- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
Only difference from 0.2.64 is supporting Qwen2.5-Math-1.5B-Instruct:
- https://github.com/mlc-ai/web-llm/pull/567
No change: https://github.com/apache/tvm/commit/a24204640efe3dcf519ca3388633a8a62a7600eb
> [Version] Bump version to 0.2.64

- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- The only change is the support of Phi-3.5-vision:
- https://github.com/mlc-ai/web-llm/pull/563
- Added `Phi-3.5-vision-instruct-q4f16_1-MLC` and `Phi-3.5-vision-instruct-q4f32_1-MLC` to prebuilt model list
- See `examples/vision-model` on how to use vision language model in WebLLM
- Compiled at https://github.com/apache/tvm/commit/931efc72b2a80d3d21c227324217de9ce76256ca
- Cherry-picked https://github.com/apache/tvm/pull/17404 on top
- Note this does not require us to recompile non-vision models because text-only inputs will not need embeddings concatenation
- WASMs: still the same `v0_2_48` WASMs
> [Version] Bump version to 0.2.65

- src/llm_chat.ts
Prior to this PR, when reusing the same engine but for different schema will run into error "Module has already been disposed". An example to reproduce this is included in https://github.com/mlc-ai/web-llm/issues/560.
This is because `this.tokenTable` is a `tvmjs.TVMObject` and will be disposed after the scope ends.
We fix this by wrapping the call with `this.tvm.detachFromCurrentScope()`, and only dispose `this.tokenTable` when we dispose the entire `LLMChatPipeline`.
> [Fix][Grammar] Detach token table to prevent disposing it

- README.md
- cleanup-index-js.sh
- package-lock.json
- package.json
- scripts/prep_deps.sh
- src/cache_util.ts
- src/embedding.ts
- src/engine.ts
- src/extension_service_worker.ts
- src/grammar.ts
- src/llm_chat.ts
- src/service_worker.ts
- utils/vram_requirements/package.json
- utils/vram_requirements/src/vram_requirements.ts
In the past, building WebLLM from source could be cumbersome as users needed to build TVMjs by themselves by setting up `emscripten` and running `./scripts/prep_deps.sh`, while TVMjs is, most of the time, not where the users may want to modify the code.
This PR modifies `package.json`'s `"tvmjs": "file:./tvm_home/web",` to `"@mlc-ai/tvmjs": "0.18.0-dev0",`, as we uploaded TVMjs as an npm package, so users no longer need to run `./scripts/prep_deps.sh`.
We update `README.md`'s directions for building from source accordingly.
Users can still build TVMjs from source with similar steps as before, as described in the `README.md`.
Note that an extra step required by this change is addressing `"import require$$4 from 'ws'"` and `const WebSocket = require(\"ws\")` in `lib/index.js` and …
> [Debt] Make tvmjs an npm package, simplify build from source

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
No breaking changes or API-related changes.
- https://github.com/mlc-ai/web-llm/pull/571
- https://github.com/mlc-ai/web-llm/pull/570
- This is the major change in this version, where we now depend on the packaged TVMjs: `@mlc-ai/web-runtime`. This only changes how users build WebLLM from source
- Since `@mlc-ai/web-runtime` is not an official package from `apache/tvm`, we record the commit that it is built upon in the WebLLM version bump PR, like below
- Version `0.18.0-dev0`
- Built at https://github.com/apache/tvm/commit/30fb16a5e1d564ffa8533cf154c0ba2ea06dfd43
> [Version] Bump version to 0.2.66

- src/config.ts
This PR supports Llama3.2-1B and 3B Instruct. Hence we add the following Llama3.2 models to the prebuilt list:
- `Llama-3.2-1B-Instruct-q4f16_1-MLC`
- `Llama-3.2-1B-Instruct-q4f32_1-MLC`
- `Llama-3.2-1B-Instruct-q0f16-MLC`
- `Llama-3.2-1B-Instruct-q0f32-MLC`
- `Llama-3.2-3B-Instruct-q4f16_1-MLC`
- `Llama-3.2-3B-Instruct-q4f32_1-MLC`
> [Llama] Add Llama3.2 Instruct 1B 3B to preset

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- https://github.com/mlc-ai/web-llm/pull/575
- Added the following models to the prebuilt list:
- `Llama-3.2-1B-Instruct-q4f16_1-MLC`
- `Llama-3.2-1B-Instruct-q4f32_1-MLC`
- `Llama-3.2-1B-Instruct-q0f16-MLC`
- `Llama-3.2-1B-Instruct-q0f32-MLC`
- `Llama-3.2-3B-Instruct-q4f16_1-MLC`
- `Llama-3.2-3B-Instruct-q4f32_1-MLC`
- No change, version `0.18.0-dev0` just like 0.2.66
- Built at https://github.com/apache/tvm/commit/30fb16a5e1d564ffa8533cf154c0ba2ea06dfd43
> [Version] Bump version to 0.2.67

- examples/vision-model/src/vision_model.ts
- src/support.ts
The previous implementation relied on the HTMLImageElement constuctor which is not available in worker contexts.
> [Fix] Support fetching images when using worker engine

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- [[Fix] Fix mismatch model link for Qwen2.5-0.5B-Instruct-q0f16-MLC](https://github.com/mlc-ai/web-llm/commit/d4af932978d3ba4f1aed01587a7c6b6612207c9c)
- The only change
- No change, version `0.18.0-dev0` just like 0.2.66
- Built at https://github.com/apache/tvm/commit/30fb16a5e1d564ffa8533cf154c0ba2ea06dfd43
> [Version][Minor] Bump version to 0.2.69

- README.md
- package-lock.json
- package.json
- utils/vram_requirements/package.json
This PR bumps TVMjs (i.e. `@mlc-ai/web-runtime`) from `0.18.0-dev0` to `0.18.0-dev1`.
The only change is:
- https://github.com/apache/tvm/pull/17420
TVMjs `0.18.0-dev1` is compiled at https://github.com/apache/tvm/commit/5e85443e43f9befcf8319cdc4045597aa49bf724 with https://github.com/apache/tvm/pull/17420 cherry-picked on top
This should fix:
- https://github.com/mlc-ai/web-llm/issues/572
> [TVMjs] Bump TVMjs version to fix WebGPU backward compatibility

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- https://github.com/mlc-ai/web-llm/pull/580
- Bumps TVMjs version to fix https://github.com/mlc-ai/web-llm/issues/572
Updated TVMjs to `0.18.0-dev1`, compiled at https://github.com/apache/tvm/commit/5e85443e43f9befcf8319cdc4045597aa49bf724 with https://github.com/apache/tvm/pull/17420 cherry-picked on top
- The only diff is https://github.com/apache/tvm/pull/17420
> [Version] Bump version to 0.2.70

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- This version tries to solve the same issue in `0.2.70`, which bumped TVMjs from `0.18.0-dev0` to `0.18.0.dev1`
- This version bumps from `0.18.0.dev1` to `0.18.0.dev2`
- The previous issue described in https://github.com/mlc-ai/web-llm/pull/581 was not resolved as https://github.com/apache/tvm/pull/17420 missed an `await`. `0.18.0.dev2` resolves this. Confirmed in an older version of Brave browser: `Version 1.65.133 Chromium: 124.0.6367.208 (Official Build) (arm64)`
- Updated TVMjs to `0.18.0-dev2`, compiled at https://github.com/apache/tvm/commit/5e85443e43f9befcf8319cdc4045597aa49bf724 with https://github.com/apache/tvm/pull/17420 cherry-picked on top
- The only diff is https://github.com/apache/tvm/pull/17420
> [Version] Bump version to 0.2.71

- src/index.ts
This PR exports the `ModelType` enumeration defined in `config.ts` so that clients could use it to differentiate different types of models.
> [Expose] Expose ModelType Enum

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- The only change is https://github.com/mlc-ai/web-llm/pull/594, adding models 
- `gemma-2-2b-jpn-it-q4f16_1-MLC`
- `gemma-2-2b-jpn-it-q4f32_1-MLC`
> [Version] Bump version 0.2.73

- examples/chrome-extension-webgpu-service-worker/src/manifest.json
- examples/chrome-extension-webgpu-service-worker/src/popup.ts
- examples/chrome-extension/src/manifest.json
- examples/chrome-extension/src/manifest_v2.json
Related issue: https://github.com/mlc-ai/web-llm/issues/590
Hugging Face started to use a new domain name https://cdn-lfs-us-1.hf.co besides the original https://cdn-lfs-us-1.huggingface.co in storing model weight files.
This PR updated the content security policy of the chrome extension examples to allow the extension to connect to the new domain to download weights and load the models.
> [Example] Update content security policy to include new hf lfs cdn

- README.md
The discord badge was not hyperlinking to the server properly due to quotes in the link
> Fix the discord badge in readme

- src/config.ts
This PR adds the following SmolLM2 prebuilt models:
- SmolLM2-1.7B-Instruct-q4f16_1-MLC
- SmolLM2-1.7B-Instruct-q4f32_1-MLC
- SmolLM2-360M-Instruct-q0f16-MLC
- SmolLM2-360M-Instruct-q0f32-MLC
- SmolLM2-360M-Instruct-q4f16_1-MLC
- SmolLM2-360M-Instruct-q4f132_1-MLC
- SmolLM2-135M-Instruct-q0f16-MLC
- SmolLM2-135M-Instruct-q0f32-MLC
Also removes SmolLM 1 models
> [Model] Add SmolLM2, deprecate SmolLM1

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package.json
- utils/vram_requirements/package.json
- The only change is https://github.com/mlc-ai/web-llm/pull/623, adding models 
- SmolLM2-1.7B-Instruct-q4f16_1-MLC
- SmolLM2-1.7B-Instruct-q4f32_1-MLC
- SmolLM2-360M-Instruct-q0f16-MLC
- SmolLM2-360M-Instruct-q0f32-MLC
- SmolLM2-360M-Instruct-q4f16_1-MLC
- SmolLM2-360M-Instruct-q4f132_1-MLC
- SmolLM2-135M-Instruct-q0f16-MLC
- SmolLM2-135M-Instruct-q0f32-MLC
Also removes SmolLM 1 models
> [Version] Bump version to 0.2.74

- src/config.ts
This PR delivers Qwen2.5-Coder 0.5B and 3B, as 1.5B and 7B are already supported. We add the following models to the model list:
- `Qwen2.5-Coder-3B-Instruct-q4f16_1-MLC`
- `Qwen2.5-Coder-3B-Instruct-q4f32_1-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q4f32_1-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q0f16-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q0f32-MLC`
Note that the official `config.json` of the coder models are identical to that of the chat models, so we do not need to compile new WASMs.
> [Model] Deliver Qwen2.5-Coder 0.5B and 3B

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- The only change is https://github.com/mlc-ai/web-llm/pull/627, adding models:
- `Qwen2.5-Coder-3B-Instruct-q4f16_1-MLC`
- `Qwen2.5-Coder-3B-Instruct-q4f32_1-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q4f32_1-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q0f16-MLC`
- `Qwen2.5-Coder-0.5B-Instruct-q0f32-MLC`
> [Version] Bump version to 0.2.75

- README.md
Added a contributors graph in  readme.
> ADDED : Contributors Section in the Readme

- README.md
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- https://github.com/mlc-ai/web-llm/pull/635
- Integrate with `web-xgrammar`
- Support `ResponseFormat.type == "grammar"`, where you specify an EBNF grammar string
- Add `grammar_init_ms` and `grammar_per_token_ms` to `CompletionUsage.extra` when using grammar
- Add `time_to_first_token_s` (TTFT) and `time_per_output_token_s` (TPOT), `e2e_latency_s` to `CompletionUsage.extra`
- Add `ignore_eos` to `Completion` and `ChatCompletion` requests
- https://github.com/mlc-ai/web-llm/pull/632
- Fixes of vram requirement for Qwen2.5-Coder-1.5B-Instruct model
> [Version] Bump version to 0.2.76

- src/config.ts
- src/conversation.ts
This PR adds the following models to the prebuilt list:
- `DeepSeek-R1-Distill-Qwen-7B-q4f16_1-MLC`
- `DeepSeek-R1-Distill-Qwen-7B-q4f32_1-MLC`
- `DeepSeek-R1-Distill-Llama-8B-q4f16_1-MLC`
- `DeepSeek-R1-Distill-Llama-8B-q4f32_1-MLC`
- `Hermes-3-Llama-3.2-3B-q4f16_1-MLC`
- `Hermes-3-Llama-3.2-3B-q4f32_1-MLC`
We will add `DeepSeek-R1-Distill-Qwen-1.5B` afterward, which is currently experiencing correctness issues.
Separately, we fix the handling of `role_content_sep` and `role_empty_sep` when it is `""`, which evaluates to false (currently we make it `": "`, which is inconsistent with what the model expects).
> [Model] Add DeepSeek-R1-Distill and Hermes-3-Llama-3.2

- README.md
- docs/conf.py
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- utils/vram_requirements/package.json
- The only change is https://github.com/mlc-ai/web-llm/pull/652, adding the following models:
- `DeepSeek-R1-Distill-Qwen-7B-q4f16_1-MLC`
- `DeepSeek-R1-Distill-Qwen-7B-q4f32_1-MLC`
- `DeepSeek-R1-Distill-Llama-8B-q4f16_1-MLC`
- `DeepSeek-R1-Distill-Llama-8B-q4f32_1-MLC`
- `Hermes-3-Llama-3.2-3B-q4f16_1-MLC`
- `Hermes-3-Llama-3.2-3B-q4f32_1-MLC`
> [Version] Bump version to 0.2.78

- examples/qwen3/README.md
- examples/qwen3/package.json
- examples/qwen3/src/qwen3_example.html
- examples/qwen3/src/qwen3_example.ts
- examples/simple-chat-ts/src/simple_chat.ts
- package-lock.json
- package.json
- src/config.ts
- src/conversation.ts
- src/engine.ts
- src/llm_chat.ts
- src/openai_api_protocols/chat_completion.ts
- tests/constants.ts
- tests/conversation.test.ts
- This PR adds the following Qwen3 models to WebLLM's prebuilt models:
- Qwen3-0.6B: `q0f16, q0f32, q4f16_1, q4f32_1`
- Other Qwen3: `{1.7B, 4B, 8B} x {q4f16_1, q4f32_1}`
- For MLC-LLM and TVM commit head, see https://github.com/mlc-ai/binary-mlc-llm-libs/pull/148
- In addition, we add `extra_body` field and `extra_body.enable_thinking` field to support switching between thinking and non-thinking mode. To prevent Qwen3 from thinking, use:
```
let request = {
messages: [
{
role: "user",
content: "How many r's are there in the word strawberry?",
},
],
extra_body: {
enable_thinking: false,
},
};
```
- Besides, for multi-turn conversation, it is advised to exclude the previous thinking tokens (currently in WebLLM, the speed-wise performance of doing this may not be optimized as we cannot …
> [Model] Support Qwen3 models with enable_thinking field

- README.md
- docs/conf.py
- examples/abort-reload/package.json
- examples/cache-usage/package.json
- examples/chrome-extension-webgpu-service-worker/package.json
- examples/chrome-extension/package.json
- examples/embeddings/package.json
- examples/function-calling/function-calling-manual/package.json
- examples/function-calling/function-calling-openai/package.json
- examples/get-started-web-worker/package.json
- examples/get-started/package.json
- examples/json-mode/package.json
- examples/json-schema/package.json
- examples/logit-processor/package.json
- examples/multi-models/package.json
- examples/multi-round-chat/package.json
- examples/next-simple-chat/package.json
- examples/qwen3/package.json
- examples/seed-to-reproduce/package.json
- examples/service-worker/package.json
- examples/simple-chat-ts/package.json
- examples/streaming/package.json
- examples/text-completion/package.json
- examples/vision-model/package.json
- package-lock.json
- package.json
- src/openai_api_protocols/chat_completion.ts
- utils/vram_requirements/package.json
- The only change is https://github.com/mlc-ai/web-llm/pull/686, which
- Add prebuilt models:
- Qwen3-0.6B: `q0f16, q0f32, q4f16_1, q4f32_1`
- Other Qwen3: `{1.7B, 4B, 8B} x {q4f16_1, q4f32_1}`
- Support `extra_body: {enable_thinking: false}` for qwen3 models to toggle thinking
- See `examples/qwen3` for more on Qwen3 usage
- Also bumped `web-tokenizers` package to `0.1.6` to resolve rust-related issues
> [Version] Bump version to 0.2.79
